# Compare the portable zip's base-patch files with the pre-edit backups, and summarise how far the base patch's own files
# have moved from them (BASE_TABLE/BASE_SCENE -- the original OverLlm patch files, never written by our tools since 0.4).
import zipfile, hashlib, io, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')); import lom_paths
Z = os.path.join(os.path.expanduser("~"), "Downloads", "LegendOfMortal_English_portable.zip")
z = zipfile.ZipFile(Z)
zt = z.read("Game/Mods/English/StringTable.csv")
zx = z.read("Game/BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt")
bt = open(os.path.join(lom_paths.BACKUPS, "StringTable.csv.20260912-2304.bak"), "rb").read()
bx = open(os.path.join(lom_paths.BACKUPS, "_AutoGeneratedTranslations.txt.20260912-2304.bak"), "rb").read()
lt = open(lom_paths.BASE_TABLE, "rb").read()
lx = open(lom_paths.BASE_SCENE, "rb").read()
md5 = lambda b: hashlib.md5(b).hexdigest()
print("table zip", md5(zt), len(zt), "backup", md5(bt), len(bt), "same" if zt == bt else "DIFFERENT")

def kv(b):
    d = {}
    order = []
    for line in b.decode("utf-8-sig").splitlines():
        if not line.strip() or line.startswith("//"):
            continue
        # XUnity key=value with escaped '=' as \=
        i = 0
        while True:
            i = line.find("=", i)
            if i < 0 or (i > 0 and line[i - 1] != "\\"):
                break
            i += 1
        if i <= 0:
            continue
        k, v = line[:i], line[i + 1:]
        if k not in d:
            order.append(k)
        d[k] = v
    return d
dz, db, dl = kv(zx), kv(bx), kv(lx)
changed_zb = [k for k in dz if k in db and db[k] != dz[k]]
print("xunity zip keys", len(dz), "backup keys", len(db), "backup-only", len(set(db) - set(dz)), "zip keys changed in backup", len(changed_zb))
for k in changed_zb[:5]:
    print("  ", k[:60], "|", dz[k][:60], "->", db[k][:60])
changed_bl = [k for k in db if k in dl and dl[k] != db[k]]
print("live xunity keys", len(dl), "backup keys changed in live", len(changed_bl), "live-only keys", len(set(dl) - set(db)), "backup keys missing in live", len(set(db) - set(dl)))
