using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Unity.Mono.Bootstrap;
using HarmonyLib;
using Mortal.Core;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace LOM_UI_EN
{
	public enum BaseData
	{
		Unknown,
		None,
		Pristine,
		OurEdits,
		Other
	}

	public enum BaseSummary
	{
		Absent,
		Complete,
		Partial
	}

	/// <summary>
	/// Detects the original English patch (OverLlm EnglishPatch: Binarizer, XUnity AutoTranslator + ResourceRedirector,
	/// LOM_UI_Plugin_KR, Mods/English/StringTable.csv) by what is running, not by what is listed: in BepInEx be.692 a plugin whose
	/// Awake died is still in the chainloader's list, so each component is checked for its Harmony hooks and its data. The data
	/// check compares a few sentinel lines (translation/MANIFEST.json, which keeps only hashes of their English) whose revised and
	/// original English differ, which tells whether the base patch still has its own text (Pristine; Other = a different release)
	/// or holds this mod's edits. Since 0.6 this mod ships its whole reviewed translation; when the base patch is installed its
	/// files (BaseTablePath, BaseScenePath, BaseResizeDir) are read under this mod's lines (fallback, Original), never written.
	/// Nothing here changes the base patch unless [Compat] SuppressKrPlugin or [Dev] DetachBaseMod is on.
	/// </summary>
	public static class OriginalMod
	{
		public const string BinarizerGuid = "binarizer.plugin.mortal";
		public const string XUnityGuid = "gravydevsupreme.xunity.autotranslator";
		public const string RedirectorGuid = "gravydevsupreme.xunity.resourceredirector";
		public const string KrGuid = "LegendOfMortal_UI_KR";
		public const string XUnityHarmony = "xunity.common.hookinghelper";

		public sealed class Sentinel
		{
			public string Key;
			/// <summary>Hash (TextHash) of this mod's English and of the base patch's for the key.</summary>
			public string Revised;
			public string Original;
		}

		/// <summary>First 16 hex digits of SHA-1 over the UTF-8 text: what MANIFEST.json keeps instead of the base patch's wording.</summary>
		public static string TextHash(string s)
		{
			if (s == null)
			{
				return null;
			}
			using (System.Security.Cryptography.SHA1 sha = System.Security.Cryptography.SHA1.Create())
			{
				byte[] h = sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(s));
				return BitConverter.ToString(h, 0, 8).Replace("-", "").ToLowerInvariant();
			}
		}

		/// <summary>The base patch's game data table: Mods/English/StringTable.csv, or the StringTable.csv of a folder Binarizer loads.</summary>
		public static string BaseTablePath
		{
			get
			{
				string p = Path.Combine(Path.Combine(Paths.GameRootPath, "Mods"), Path.Combine("English", "StringTable.csv"));
				if (File.Exists(p))
				{
					return p;
				}
				try
				{
					Type hook = TranslationProfiles.HookMods;
					if (hook != null && AccessTools.Field(hook, "ModPaths")?.GetValue(null) is List<string> paths)
					{
						foreach (string dir in paths)
						{
							string q = Path.Combine(dir, "StringTable.csv");
							if (File.Exists(q))
							{
								return q;
							}
						}
					}
				}
				catch (Exception)
				{
				}
				return p;
			}
		}

		/// <summary>The base patch's XUnity AutoTranslator folder (its translation file and resizers).</summary>
		public static string BaseTextDir => Path.Combine(Path.Combine(Paths.BepInExRootPath, "Translation"), Path.Combine("en", "Text"));

		public static string BaseScenePath => Path.Combine(BaseTextDir, "_AutoGeneratedTranslations.txt");

		public static IEnumerable<string> TableSentinelKeys => _tableSentinels.Select((Sentinel s) => s.Key);

		public static IEnumerable<string> SceneSentinelKeys => _sceneSentinels.Select((Sentinel s) => s.Key);

		/// <summary>The data check on values read straight from the base patch's files (for Original served from them).</summary>
		public static BaseData VoteSample(bool table, Dictionary<string, string> sample, out string detail)
		{
			if (sample == null || sample.Count == 0)
			{
				detail = "no sentinel lines in the file";
				return BaseData.Unknown;
			}
			return Vote(table ? _tableSentinels : _sceneSentinels, delegate(string k, out string v)
			{
				return sample.TryGetValue(k, out v);
			}, out detail);
		}

		public sealed class Report
		{
			public bool BinarizerInstalled;
			public bool BinarizerLoaded;
			public bool BinarizerHooked;
			public int BinarizerEntries = -1;
			public bool BinarizerEnglishFolder;
			public bool AddressablesPatched;
			public BaseData BinarizerData = BaseData.Unknown;
			public bool XUnityInstalled;
			public bool XUnityLoaded;
			public bool XUnityRunning;
			public bool XUnityHooked;
			public BaseData XUnityData = BaseData.Unknown;
			public bool RedirectorLoaded;
			public bool KrInstalled;
			public bool KrLoaded;
			public bool KrHooked;
			public bool KrSuppressed;
			public bool BaseTableFile;
			public bool BaseSceneFile;
			public bool Detached;
			public string BinarizerVote = "";
			public string XUnityVote = "";

			/// <summary>Any of the base patch's plugins or text files is on disk (this mod reads the text files itself).</summary>
			public bool AnyInstalled => BinarizerInstalled || XUnityInstalled || KrInstalled || BaseTableFile || BaseSceneFile;

			/// <summary>The base patch's English is on disk for this mod to lay its revisions over.</summary>
			public bool TextInstalled => BaseTableFile || BaseSceneFile;

			public BaseSummary Summary
			{
				get
				{
					if (!AnyInstalled)
					{
						return BaseSummary.Absent;
					}
					if (BinarizerHooked && BinarizerEntries > 0 && XUnityRunning && XUnityHooked && BaseSceneFile)
					{
						return BaseSummary.Complete;
					}
					return BaseSummary.Partial;
				}
			}

			/// <summary>Binarizer runs with its own (non-revised) table, so the Original table can be left to it.</summary>
			public bool TableHandBack => !Detached && BinarizerHooked && BinarizerEntries > 0 && (BinarizerData == BaseData.Pristine || BinarizerData == BaseData.Other);

			/// <summary>XUnity runs with its own (non-revised) lines, so Original scene text can be left to it.</summary>
			public bool SceneHandBack => !Detached && XUnityRunning && XUnityHooked && (XUnityData == BaseData.Pristine || XUnityData == BaseData.Other);

			public List<string> Diagnoses()
			{
				List<string> d = new List<string>();
				if (Detached)
				{
					d.Add("detached for testing ([Dev] DetachBaseMod): its hooks were removed at startup");
				}
				if (BinarizerInstalled && !BinarizerHooked)
				{
					d.Add(AddressablesPatched ? "Binarizer is installed but not running" : "Binarizer is installed but not running: Unity.Addressables.dll is the stock copy (a Steam update or file check replaces the patched one); this mod does not need it");
				}
				else if (BinarizerHooked && BinarizerEntries <= 0)
				{
					d.Add("Binarizer is running with no English table (Mods/English/StringTable.csv)");
				}
				if (XUnityInstalled && !XUnityRunning)
				{
					d.Add("XUnity AutoTranslator is installed but not running");
				}
				if (XUnityRunning && !BinarizerHooked)
				{
					d.Add("XUnity AutoTranslator runs without Binarizer");
				}
				if (BinarizerHooked && !XUnityRunning)
				{
					d.Add("Binarizer runs without XUnity AutoTranslator");
				}
				if (BinarizerData == BaseData.OurEdits || XUnityData == BaseData.OurEdits)
				{
					d.Add("its files contain this mod's edits (" + ((BinarizerData == BaseData.OurEdits) ? "string table" : "") + ((BinarizerData == BaseData.OurEdits && XUnityData == BaseData.OurEdits) ? " and " : "") + ((XUnityData == BaseData.OurEdits) ? "scene lines" : "") + "); Original cannot show its own text until the patch is reinstalled");
				}
				if (AnyInstalled && !BaseTableFile)
				{
					d.Add("its game data table (Mods/English/StringTable.csv) is missing" + (TranslationProfiles.OwnTableComplete ? " (this mod's own table covers the game data text)" : ": only this mod's own game data lines are in English"));
				}
				if (AnyInstalled && !BaseSceneFile)
				{
					d.Add("its scene text file (BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt) is missing" + (TranslationProfiles.OwnSceneComplete ? " (this mod's own scene lines cover the scene text)" : ": only this mod's own scene lines are in English"));
				}
				if (XUnityRunning && !XUnityHooked)
				{
					d.Add("XUnity AutoTranslator runs but its text hooks are missing");
				}
				if (KrInstalled && !BinarizerInstalled && !XUnityInstalled && !TextInstalled)
				{
					d.Add("only its LOM_UI_Plugin_KR layout plugin is installed (its fixes are also built into this mod)");
				}
				if (d.Count == 0 && Summary == BaseSummary.Partial)
				{
					d.Add("some of its files are present but it is not fully running");
				}
				return d;
			}
		}

		public static ConfigEntry<bool> CfgSuppressKr;
		public static ConfigEntry<bool> CfgDetach;

		private static List<Sentinel> _tableSentinels = new List<Sentinel>();
		private static List<Sentinel> _sceneSentinels = new List<Sentinel>();
		private static int _sceneChecks;
		private static bool _lateDone;
		private static bool _detached;
		private static bool _krSuppressed;
		private static Harmony _neutralizer;
		private static readonly HashSet<MethodInfo> _neutralized = new HashSet<MethodInfo>();

		public static Report Current { get; private set; } = new Report();

		public static string ManifestPath => Path.Combine(TranslationProfiles.TranslationDir, "MANIFEST.json");

		public static string ManifestError { get; private set; }

		/// <summary>MANIFEST.json "standalone" (publish.py, since 0.6): the table rows and scene lines this mod ships and the full
		/// working copy's counts at publish time (TranslationProfiles.OwnTableComplete compares them); -1 when the manifest has
		/// none (an overlay that needs the OverLlm patch's text for most of the game).</summary>
		public static int ManifestTableRows { get; private set; } = -1;
		public static int ManifestTableTotal { get; private set; } = -1;
		public static int ManifestSceneLines { get; private set; } = -1;
		public static int ManifestSceneTotal { get; private set; } = -1;

		/// <summary>Raised when the report changes in a way that can change which engine serves a layer.</summary>
		public static event Action Changed;

		public static void Bind(ConfigFile cfg)
		{
			CfgSuppressKr = cfg.Bind("Compat", "SuppressKrPlugin", false, "Remove the Harmony patches of LOM_UI_Plugin_KR (the Korean layout plugin that comes with " + Plugin.BaseModName + ") at startup. Its layout fixes are built into this mod's rules, so this only drops its per-object SetActive hook. Turning it back off needs a restart.");
			CfgDetach = cfg.Bind("Dev", "DetachBaseMod", false, "Testing only: at startup remove every Harmony patch of " + Plugin.BaseModName + " (Binarizer, XUnity AutoTranslator, LOM_UI_Plugin_KR) and disable its components, to see this mod running on its own without uninstalling anything. Needs a restart both ways.");
			LoadManifest();
		}

		private static void LoadManifest()
		{
			_tableSentinels = new List<Sentinel>();
			_sceneSentinels = new List<Sentinel>();
			ManifestError = null;
			ManifestTableRows = ManifestTableTotal = ManifestSceneLines = ManifestSceneTotal = -1;
			try
			{
				if (!File.Exists(ManifestPath))
				{
					ManifestError = "translation/MANIFEST.json is missing";
					return;
				}
				JObject m = JObject.Parse(File.ReadAllText(ManifestPath));
				_tableSentinels = ReadSentinels(m["table_sentinels"]);
				_sceneSentinels = ReadSentinels(m["scene_sentinels"]);
				if (m["standalone"] is JObject sa)
				{
					ManifestTableRows = Count(sa["table_rows"]);
					ManifestTableTotal = Count(sa["table_total"]);
					ManifestSceneLines = Count(sa["scene_lines"]);
					ManifestSceneTotal = Count(sa["scene_total"]);
				}
			}
			catch (Exception ex)
			{
				ManifestError = "MANIFEST.json: " + ex.Message;
			}
		}

		private static int Count(JToken t)
		{
			return (t != null && t.Type == JTokenType.Integer) ? (int)t : -1;
		}

		private static List<Sentinel> ReadSentinels(JToken t)
		{
			List<Sentinel> list = new List<Sentinel>();
			if (t is JArray arr)
			{
				foreach (JToken e in arr)
				{
					string k = (string)e["key"];
					// Hashes since 0.5 (no base-patch text in this mod); plain values from 0.4 manifests are hashed here.
					string r = (string)e["revised_sha1"] ?? TextHash((string)e["revised"]);
					string o = (string)e["original_sha1"] ?? TextHash((string)e["original"]);
					if (!string.IsNullOrEmpty(k) && r != null && o != null && r != o)
					{
						list.Add(new Sentinel
						{
							Key = k,
							Revised = r,
							Original = o
						});
					}
				}
			}
			return list;
		}

		/// <summary>Plugin.Awake: the base patch's plugins load before ours (soft dependencies), so their hooks and tables exist.</summary>
		// In its own method: a game without LeanLocalizationResolver fails here (caught by the caller), not the whole detection.
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
		private static MethodInfo ResolverGetString()
		{
			return AccessTools.Method(typeof(LeanLocalizationResolver), "GetString", new Type[1] { typeof(string) });
		}

		public static void DetectEarly()
		{
			Current = Detect(Current);
			Plugin.Log.LogInfo("base patch: " + Describe(Current));
			try
			{
				UnityChainloader.Instance.Finished += DetectLate;
			}
			catch (Exception ex)
			{
				Plugin.Log.LogWarning("chainloader Finished event not reachable: " + ex.Message);
			}
		}

		/// <summary>After every plugin has loaded: suppression and detach run here, then the report is taken again.</summary>
		public static void DetectLate()
		{
			if (_lateDone)
			{
				return;
			}
			_lateDone = true;
			try
			{
				if (CfgDetach.Value)
				{
					Detach();
				}
				else if (CfgSuppressKr.Value)
				{
					SuppressKr();
				}
			}
			catch (Exception ex)
			{
				Plugin.Log.LogError("base patch detach/suppress failed: " + ex);
			}
			// Current is still the report from before the detach, so the comparison in Update sees what changed.
			Update(Detect(Current));
		}

		/// <summary>sceneLoaded: XUnity loads its cache after the plugins, so its data state is retried on the first few scene loads.</summary>
		public static void OnSceneLoaded()
		{
			if (!_lateDone)
			{
				DetectLate();
			}
			if (Current.XUnityData != BaseData.Unknown || _sceneChecks >= 3)
			{
				return;
			}
			_sceneChecks++;
			Update(Detect(Current));
		}

		private static void Update(Report next)
		{
			Report old = Current;
			Current = next;
			if (old.TableHandBack != next.TableHandBack || old.SceneHandBack != next.SceneHandBack || old.XUnityData != next.XUnityData || old.BinarizerData != next.BinarizerData || old.Detached != next.Detached || old.BinarizerHooked != next.BinarizerHooked || old.XUnityHooked != next.XUnityHooked || old.XUnityRunning != next.XUnityRunning)
			{
				Plugin.Log.LogInfo("base patch: " + Describe(next));
				try
				{
					Changed?.Invoke();
				}
				catch (Exception ex)
				{
					Plugin.Log.LogError("base patch change handler failed: " + ex);
				}
			}
		}

		public static void Refresh()
		{
			Update(Detect(Current));
		}

		private static Report Detect(Report previous)
		{
			Report r = new Report
			{
				KrSuppressed = _krSuppressed,
				Detached = _detached
			};
			try
			{
				string plugins = Paths.PluginPath;
				r.BinarizerInstalled = FindFile(plugins, "FunctionalPlugin_Binarizer.dll");
				r.XUnityInstalled = Directory.Exists(Path.Combine(plugins, "XUnity.AutoTranslator")) || FindFile(plugins, "XUnity.AutoTranslator.Plugin.Core.dll");
				r.KrInstalled = FindFile(plugins, "LOM_UI_Plugin_KR.dll");
				r.BaseTableFile = File.Exists(BaseTablePath);
				r.BaseSceneFile = File.Exists(BaseScenePath);
			}
			catch (Exception ex)
			{
				Plugin.Log.LogWarning("base patch file check failed: " + ex.Message);
			}
			try
			{
				r.BinarizerLoaded = Loaded(BinarizerGuid);
				r.XUnityLoaded = Loaded(XUnityGuid);
				r.RedirectorLoaded = Loaded(RedirectorGuid);
				r.KrLoaded = Loaded(KrGuid);
			}
			catch (Exception ex)
			{
				Plugin.Log.LogWarning("chainloader check failed: " + ex.Message);
			}
			try
			{
				MethodInfo getString = ResolverGetString();
				Patches info = (getString == null) ? null : Harmony.GetPatchInfo(getString);
				r.BinarizerHooked = info != null && info.Prefixes.Any((Patch p) => p.PatchMethod?.DeclaringType?.FullName == "Mortal.HookMods");
				r.XUnityHooked = Harmony.HasAnyPatches(XUnityHarmony) && !_detached;
				r.KrHooked = Harmony.HasAnyPatches(KrGuid) && !_krSuppressed;
			}
			catch (Exception ex)
			{
				Plugin.Log.LogWarning("Harmony patch check failed: " + ex.Message);
			}
			try
			{
				Type hook = TranslationProfiles.HookMods;
				if (hook != null)
				{
					Dictionary<string, string> map = AccessTools.Field(hook, "mapString")?.GetValue(null) as Dictionary<string, string>;
					r.BinarizerEntries = map?.Count ?? -1;
					if (AccessTools.Field(hook, "ModPaths")?.GetValue(null) is List<string> paths)
					{
						r.BinarizerEnglishFolder = paths.Any((string p) => string.Equals(Path.GetFileName(p.TrimEnd('/', '\\')), "English", StringComparison.OrdinalIgnoreCase));
					}
					r.BinarizerData = (map == null || map.Count == 0) ? BaseData.None : Vote(_tableSentinels, delegate(string k, out string v)
					{
						return map.TryGetValue(k, out v);
					}, out r.BinarizerVote);
				}
				else
				{
					r.BinarizerData = BaseData.None;
				}
				Type addressables = TranslationProfiles.FindType("Unity.Addressables", "UnityEngine.AddressableAssets.Addressables");
				r.AddressablesPatched = addressables != null && AccessTools.Field(addressables, "ModPaths") != null;
			}
			catch (Exception ex)
			{
				Plugin.Log.LogWarning("Binarizer table check failed: " + ex.Message);
			}
			try
			{
				Type plugin = TranslationProfiles.FindType("XUnity.AutoTranslator.Plugin.Core", "XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin");
				object current = (plugin == null) ? null : AccessTools.Field(plugin, "Current")?.GetValue(null);
				r.XUnityRunning = current is Behaviour b && b != null && b.enabled;
				if (!r.XUnityRunning)
				{
					r.XUnityData = BaseData.None;
				}
				else if (previous.XUnityData != BaseData.Unknown && previous.XUnityData != BaseData.None)
				{
					r.XUnityData = previous.XUnityData;
					r.XUnityVote = previous.XUnityVote;
				}
				else
				{
					r.XUnityData = Vote(_sceneSentinels, XUnityBridge.TryTranslate, out r.XUnityVote);
				}
			}
			catch (Exception ex)
			{
				Plugin.Log.LogWarning("XUnity check failed: " + ex.Message);
			}
			return r;
		}

		private delegate bool Lookup(string key, out string value);

		/// <summary>At least two thirds of the sentinels answering with the original (or the revised) English decide; too few answers = Unknown.</summary>
		private static BaseData Vote(List<Sentinel> sentinels, Lookup lookup, out string detail)
		{
			int n = sentinels.Count;
			if (n == 0)
			{
				detail = "no sentinels";
				return BaseData.Unknown;
			}
			int original = 0;
			int revised = 0;
			int answered = 0;
			foreach (Sentinel s in sentinels)
			{
				string v;
				if (!lookup(s.Key, out v) || v == null)
				{
					continue;
				}
				answered++;
				string h = TextHash(v);
				if (h == s.Original)
				{
					original++;
				}
				else if (h == s.Revised)
				{
					revised++;
				}
			}
			detail = $"{original} original, {revised} revised, {answered - original - revised} other of {n}";
			if (answered * 3 < n * 2)
			{
				return BaseData.Unknown;
			}
			if (original * 3 >= n * 2)
			{
				return BaseData.Pristine;
			}
			// A meaningful share of this mod's wording means the files hold (some of) our edits, e.g. a partial restore: never
			// hand Original to them. Other is a base patch whose text is mostly neither, i.e. a different release.
			if (revised * 3 >= n)
			{
				return BaseData.OurEdits;
			}
			return BaseData.Other;
		}

		private static bool Loaded(string guid)
		{
			UnityChainloader cl = UnityChainloader.Instance;
			PluginInfo pi;
			return cl != null && cl.Plugins.TryGetValue(guid, out pi) && pi != null && pi.Instance != null;
		}

		private static bool FindFile(string root, string name)
		{
			if (!Directory.Exists(root))
			{
				return false;
			}
			if (File.Exists(Path.Combine(root, name)))
			{
				return true;
			}
			foreach (string d in Directory.GetDirectories(root))
			{
				if (File.Exists(Path.Combine(d, name)))
				{
					return true;
				}
				try
				{
					foreach (string d2 in Directory.GetDirectories(d))
					{
						if (File.Exists(Path.Combine(d2, name)))
						{
							return true;
						}
					}
				}
				catch (Exception)
				{
				}
			}
			return false;
		}

		private static void SuppressKr()
		{
			if (!Harmony.HasAnyPatches(KrGuid))
			{
				return;
			}
			Harmony.UnpatchID(KrGuid);
			int inert = Neutralize((Patch p) => p.owner == KrGuid);
			_krSuppressed = true;
			Plugin.Log.LogInfo("LOM_UI_Plugin_KR: its Harmony patches were removed ([Compat] SuppressKrPlugin)" + ((inert > 0) ? $"; {inert} on native Unity methods (GameObject.SetActive) cannot be removed and were made inert" : ""));
		}

		/// <summary>
		/// Makes the matching patch methods do nothing (a skip prefix on the patch method itself, the way PerfPatches quiets
		/// Binarizer): a void patch returns at once, a bool prefix returns true (run the original). Other return types are left.
		/// </summary>
		private static int Neutralize(Func<Patch, bool> match)
		{
			if (_neutralizer == null)
			{
				_neutralizer = new Harmony("lom.ui.english.neutralize");
			}
			int n = 0;
			foreach (MethodBase m in Harmony.GetAllPatchedMethods().ToList())
			{
				Patches info = Harmony.GetPatchInfo(m);
				if (info == null)
				{
					continue;
				}
				foreach (Patch p in info.Prefixes.Concat(info.Postfixes).Concat(info.Finalizers).ToList())
				{
					MethodInfo pm = p.PatchMethod;
					if (pm == null || !match(p) || _neutralized.Contains(pm))
					{
						continue;
					}
					string skip = (pm.ReturnType == typeof(void)) ? nameof(SkipVoid) : ((pm.ReturnType == typeof(bool)) ? nameof(SkipBool) : null);
					if (skip == null)
					{
						continue;
					}
					try
					{
						_neutralizer.Patch(pm, new HarmonyMethod(typeof(OriginalMod), skip)
						{
							priority = Priority.First
						});
						_neutralized.Add(pm);
						n++;
					}
					catch (Exception ex)
					{
						Plugin.Log.LogWarning("could not neutralize " + pm.DeclaringType?.FullName + "." + pm.Name + ": " + ex.Message);
					}
				}
			}
			return n;
		}

		private static bool SkipVoid()
		{
			return false;
		}

		private static bool SkipBool(ref bool __result)
		{
			__result = true;
			return false;
		}

		/// <summary>Patches of these owners are still registered but made inert (native-method patches that cannot be removed).</summary>
		public static int NeutralizedCount => _neutralized.Count;

		/// <summary>[Dev] DetachBaseMod: simulates an uninstalled base patch without touching its files.</summary>
		private static void Detach()
		{
			int owners = 0;
			HashSet<string> ids = new HashSet<string>(StringComparer.Ordinal)
			{
				XUnityHarmony,
				KrGuid
			};
			foreach (MethodBase m in Harmony.GetAllPatchedMethods().ToList())
			{
				Patches info = Harmony.GetPatchInfo(m);
				if (info == null)
				{
					continue;
				}
				foreach (Patch p in info.Prefixes.Concat(info.Postfixes).Concat(info.Transpilers).Concat(info.Finalizers))
				{
					string asm = p.PatchMethod?.DeclaringType?.Assembly.GetName().Name;
					if (asm == "FunctionalPlugin_Binarizer" || (asm != null && asm.StartsWith("XUnity.", StringComparison.Ordinal)) || asm == "LOM_UI_Plugin_KR")
					{
						ids.Add(p.owner);
					}
				}
			}
			ids.Remove(Plugin.GUID);
			ids.Remove(StringsPlugin.GUID);
			foreach (string id in ids)
			{
				if (Harmony.HasAnyPatches(id))
				{
					Harmony.UnpatchID(id);
					owners++;
				}
			}
			// HarmonyX cannot unpatch native Unity methods (GameObject.SetActive, TextMesh.text): make those patch methods inert.
			int inert = Neutralize((Patch p) => ids.Contains(p.owner));
			if (inert > 0)
			{
				Plugin.Log.LogInfo($"[Dev] DetachBaseMod: {inert} patches on native Unity methods could not be removed and were made inert");
			}
			_krSuppressed = true;
			foreach (string guid in new string[3] { BinarizerGuid, XUnityGuid, RedirectorGuid })
			{
				try
				{
					UnityChainloader cl = UnityChainloader.Instance;
					PluginInfo pi;
					if (cl != null && cl.Plugins.TryGetValue(guid, out pi) && pi?.Instance is Behaviour b && b != null)
					{
						b.enabled = false;
					}
				}
				catch (Exception)
				{
				}
			}
			try
			{
				// The chainloader's XUnity entry is only the BepInEx wrapper; the component that runs is AutoTranslationPlugin.Current.
				Type xua = TranslationProfiles.FindType("XUnity.AutoTranslator.Plugin.Core", "XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin");
				if (xua != null && AccessTools.Field(xua, "Current")?.GetValue(null) is Behaviour running && running != null)
				{
					running.enabled = false;
				}
			}
			catch (Exception)
			{
			}
			try
			{
				Type addressables = TranslationProfiles.FindType("Unity.Addressables", "UnityEngine.AddressableAssets.Addressables");
				FieldInfo modPaths = (addressables == null) ? null : AccessTools.Field(addressables, "ModPaths");
				if (modPaths != null && !modPaths.FieldType.IsValueType)
				{
					modPaths.SetValue(null, null);
				}
			}
			catch (Exception)
			{
			}
			_detached = true;
			Plugin.Log.LogWarning($"[Dev] DetachBaseMod: removed the Harmony patches of {owners} base-patch owner(s) and disabled its plugins; restart with the setting off to restore them");
		}

		public static string Describe(Report r)
		{
			string s;
			switch (r.Summary)
			{
			case BaseSummary.Absent:
				s = TranslationProfiles.OwnComplete ? "not installed (optional: this mod's own translation is complete)" : "not installed (only this mod's own lines are in English)";
				break;
			case BaseSummary.Complete:
				s = "installed and running";
				break;
			default:
				s = "partly installed";
				break;
			}
			s += $" (Binarizer {Flags(r.BinarizerInstalled, r.BinarizerLoaded, r.BinarizerHooked)}, {((r.BinarizerEntries >= 0) ? (r.BinarizerEntries + " keys") : "no table")}, data {r.BinarizerData}{(string.IsNullOrEmpty(r.BinarizerVote) ? "" : (" [" + r.BinarizerVote + "]"))}; XUnity {Flags(r.XUnityInstalled, r.XUnityRunning, r.XUnityHooked)}, data {r.XUnityData}{(string.IsNullOrEmpty(r.XUnityVote) ? "" : (" [" + r.XUnityVote + "]"))}; KR {Flags(r.KrInstalled, r.KrLoaded, r.KrHooked)}{(r.KrSuppressed ? " suppressed" : "")})";
			List<string> d = r.Diagnoses();
			if (d.Count > 0)
			{
				s += ": " + string.Join("; ", d);
			}
			if (ManifestError != null)
			{
				s += " [" + ManifestError + "]";
			}
			return s;
		}

		private static string Flags(bool installed, bool loaded, bool hooked)
		{
			if (!installed && !loaded)
			{
				return "absent";
			}
			return (installed ? "installed" : "not on disk") + (loaded ? "/loaded" : "") + (hooked ? "/hooked" : "/not hooked");
		}
	}
}
