using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading;
using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;
using UnityEngine;

namespace LOM_UI_EN
{
	public enum TextSource
	{
		Revised,
		Original,
		/// <summary>This mod adds no text for the layer: the original patch (if installed) or the game's own text shows.</summary>
		Off
	}

	/// <summary>What actually renders a text layer right now.</summary>
	public enum LayerMode
	{
		/// <summary>This mod's revised lines laid over the original patch's own text (or alone, when that is not installed).</summary>
		Revised,
		/// <summary>Original text, left to the running base patch (Binarizer / XUnity AutoTranslator with its own files).</summary>
		OriginalHandBack,
		/// <summary>Original text served by this mod, read from the original patch's installed files (its plugins are not running).</summary>
		OriginalFromFiles,
		/// <summary>This mod's revised files could not be read; the base patch serves whatever it has.</summary>
		BaseOnly,
		/// <summary>Nothing serves the layer (no file, no base patch): the game shows its Chinese text.</summary>
		Off
	}

	/// <summary>
	/// Chooses, per text layer, which engine serves it and with which data, and switches live:
	///   data table  (LocaleResolver.GetString: items, arts, stats, names, menus, story lines) - TextTable
	///   scene text  (Chinese drawn into Text/TMP components: labels, buttons, dice, battle lines) - SceneText
	/// This mod ships its own lines (plugins/LOM_UI_EN/translation: since 0.6 the whole reviewed translation, so it plays in English
	/// alone): Revised lays them over the original OverLlm patch's installed files when that patch is there (Mods/English/
	/// StringTable.csv, XUnity's _AutoGeneratedTranslations.txt and resizers, read in place), which then fill only what this mod
	/// lacks and serve the fallback. Original hands a layer back to the base patch when that part of it runs
	/// with its own text (OriginalMod decides), or reads its files when its plugins do not run. The base patch's files are only
	/// read, never written (the reviewed lines that kept its wording are credited in THIRD_PARTY_NOTICES.txt).
	/// </summary>
	public static class TranslationProfiles
	{
		public static ConfigEntry<TextSource> CfgTable;
		public static ConfigEntry<TextSource> CfgScene;

		/// <summary>The data check on the base patch's files as this mod read them (Unknown until read).</summary>
		public static BaseData TableFileData { get; private set; } = BaseData.Unknown;
		public static BaseData SceneFileData { get; private set; } = BaseData.Unknown;
		public static string TableFileVote { get; private set; } = "";
		public static string SceneFileVote { get; private set; } = "";

		private static TextTable.Table _tableRevised;
		private static TextTable.Table _tableOriginal;
		private static SceneDictionary _sceneRevised;
		private static SceneDictionary _sceneOriginal;
		private static bool _tableRevisedTried;
		private static bool _sceneRevisedTried;
		private static bool _started;

		public static LayerMode TableMode { get; private set; } = LayerMode.Off;
		public static LayerMode SceneMode { get; private set; } = LayerMode.Off;

		public static string TableError { get; private set; }
		public static string SceneError { get; private set; }

		/// <summary>Why the configured Original could not be used for a layer (then it shows the revised text), or null.</summary>
		public static string TableOriginalProblem { get; private set; }
		public static string SceneOriginalProblem { get; private set; }

		public static string TranslationDir => Path.Combine(Plugin.PluginDir, "translation");
		/// <summary>This mod's revised game data rows (only rows it changed or added).</summary>
		public static string RevisedTablePath => Path.Combine(TranslationDir, "StringTable.csv");
		/// <summary>This mod's revised scene lines (*.txt: lines it changed or added; an empty value removes the base line).</summary>
		public static string RevisedSceneDir => Path.Combine(TranslationDir, "scene");
		/// <summary>This mod's own resizer files, if any (the original patch's are read from its folder).</summary>
		public static string ResizeDir => Path.Combine(RevisedSceneDir, "resize");
		public static string BaseResizeDir => OriginalMod.BaseTextDir;

		public static int TableEntries => TextTable.Active?.Count ?? 0;
		public static int SceneEntries => SceneText.Active?.Entries ?? 0;
		public static int RevisedTableEntries => _tableRevised?.Count ?? 0;
		public static int RevisedSceneEntries => _sceneRevised?.Entries ?? 0;
		/// <summary>This mod's own rows and lines in the revised layers, and whether the original patch's text is under them.</summary>
		public static int OwnTableRows => _tableRevised?.OverlayCount ?? 0;
		public static int OwnSceneLines => _sceneRevised?.OverlayEntries ?? 0;
		public static bool TableHasBase => _tableRevised != null && _tableRevised.BasePath != null;
		/// <summary>The revised table's record carries game-text hashes (what the game-update check needs), not just OverLlm-line hashes.</summary>
		public static bool TableHasRecords => _tableRevised != null && _tableRevised.Fallback.HashedKeys.Count > 0;
		public static bool SceneHasBase => _sceneRevised != null && _sceneRevised.BaseFile != null;

		/// <summary>The share of the full translation (MANIFEST.json "standalone") this mod's own files must carry for a layer to
		/// play in English without the OverLlm patch.</summary>
		public const double CompleteShare = 0.98;
		/// <summary>This mod's own table carries the game data text by itself: it shipped (nearly) every row of the full working
		/// copy, and what loaded is what shipped (before the table loads, the manifest's word stands; a load that was tried and
		/// failed carries nothing).</summary>
		public static bool OwnTableComplete => Covers(OriginalMod.ManifestTableRows, OriginalMod.ManifestTableTotal, (_tableRevised != null) ? OwnTableRows : (_tableRevisedTried ? 0 : (-1)));
		/// <summary>The same for the scene lines.</summary>
		public static bool OwnSceneComplete => Covers(OriginalMod.ManifestSceneLines, OriginalMod.ManifestSceneTotal, (_sceneRevised != null) ? OwnSceneLines : (_sceneRevisedTried ? 0 : (-1)));
		/// <summary>Both layers: the game plays in English with this mod alone.</summary>
		public static bool OwnComplete => OwnTableComplete && OwnSceneComplete;

		private static bool Covers(int shipped, int total, int loaded)
		{
			if (shipped <= 0 || total <= 0 || shipped < CompleteShare * total)
			{
				return false;
			}
			// A load far short of what shipped (a damaged or partly copied file) is not complete. A published file loads at least
			// its shipped count (the scene count adds the removal lines); the margin only absorbs hand edits.
			return loaded < 0 || loaded >= 0.9 * shipped;
		}

		private static Type _hookMods;
		private static bool _hookModsResolved;

		/// <summary>
		/// A type from one named assembly. AccessTools.TypeByName walks the types of every loaded assembly when the fast lookup
		/// misses, and NAudio's throw a ReflectionTypeLoadException that HarmonyX logs as a warning each time.
		/// </summary>
		internal static Type FindType(string assembly, string fullName)
		{
			foreach (Assembly a in AppDomain.CurrentDomain.GetAssemblies())
			{
				try
				{
					if (a.GetName().Name == assembly)
					{
						Type t = a.GetType(fullName, throwOnError: false);
						if (t != null)
						{
							return t;
						}
					}
				}
				catch (Exception)
				{
				}
			}
			return null;
		}

		internal static Type HookMods
		{
			get
			{
				if (!_hookModsResolved)
				{
					_hookModsResolved = true;
					_hookMods = FindType("FunctionalPlugin_Binarizer", "Mortal.HookMods");
				}
				return _hookMods;
			}
		}

		public static void Bind(ConfigFile cfg)
		{
			CfgTable = cfg.Bind("Translation", "DataTableText", TextSource.Revised, "Game data text: items, martial arts, stats, names, menus and story lines, looked up by key. Revised = this mod's own rows (plugins/LOM_UI_EN/translation/StringTable.csv, the whole reviewed translation), over the table of " + Plugin.BaseModName + " (Mods/English/StringTable.csv) when that patch is installed, which then fills only rows this mod lacks. Original = the text of " + Plugin.BaseModName + ": left to its Binarizer when that runs, otherwise read from its table file. Off = this mod adds no game data text (" + Plugin.BaseModName + ", if running, serves its own). Switches live.");
			TextTable.CfgFallback = cfg.Bind("Translation", "FallBackToOriginal", true, "With " + Plugin.BaseModName + " installed: when one of this mod's game data lines no longer fits the game, show the patch's line instead. A line no longer fits when the game's own text for it changed since it was revised (a game update) and the patch has a newer line, or when it uses a placeholder ({0}, {$var}) the game's text no longer has. Scene text falls back by itself: its lines are matched by the game's Chinese, so a changed line finds the patch's line for the new text. Off = always this mod's line. Switches live.");
			TextTable.CfgFallback.SettingChanged += delegate
			{
				TextTable.ClearDecisions();
			};
			CfgScene = cfg.Bind("Translation", "SceneText", TextSource.Revised, "Scene text: labels, buttons, captions, dice and battle lines drawn into the screens, matched by their Chinese text. Revised = this mod's own lines and resizers (plugins/LOM_UI_EN/translation/scene/), over the XUnity file of " + Plugin.BaseModName + " (BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt and its resizers) when that patch is installed, which then fills only lines this mod lacks. Original = the lines of " + Plugin.BaseModName + ": left to its XUnity AutoTranslator when that runs, otherwise read from its file. Off = this mod adds no scene text (" + Plugin.BaseModName + ", if running, translates on its own). Switches live.");
		}

		/// <summary>Plugin.Awake, after OriginalMod.DetectEarly: loads the configured data (the table and the scene lines in parallel) and installs it before any scene asks for text.</summary>
		public static void ApplyStartup()
		{
			try
			{
				ApplyStartupCore();
			}
			catch (Exception ex)
			{
				Plugin.Log.LogError("translation startup failed; the original patch (if installed) serves the text: " + ex);
				F.GameText.Problems.Add("startup failed: " + ex.Message);
				F.SceneText.Problems.Add("startup failed: " + ex.Message);
				TableError = TableError ?? ("startup failed: " + ex.Message);
				SceneError = SceneError ?? ("startup failed: " + ex.Message);
				TextTable.Use(null);
				SceneText.Use(null, "off", null);
			}
		}

		private static void ApplyStartupCore()
		{
			_started = true;
			// First, so a later detection change (or a settings switch) still applies the layers if this startup fails part-way.
			OriginalMod.Changed += delegate
			{
				Apply(retranslate: true);
			};
			Thread sceneThread = null;
			SceneDictionary preloaded = null;
			Exception sceneFailure = null;
			if (CfgScene.Value == TextSource.Revised || (CfgScene.Value == TextSource.Original && !OriginalMod.Current.SceneHandBack))
			{
				bool revised = CfgScene.Value == TextSource.Revised || !File.Exists(OriginalMod.BaseScenePath);
				sceneThread = new Thread(delegate()
				{
					try
					{
						preloaded = revised ? LoadSceneRevisedCore() : LoadSceneOriginalCore();
					}
					catch (Exception ex)
					{
						sceneFailure = ex;
					}
				})
				{
					IsBackground = true,
					Name = "LOM_UI_EN scene text load"
				};
				sceneThread.Start();
				if (revised)
				{
					_sceneRevisedTried = true;
				}
			}
			Stopwatch sw = Stopwatch.StartNew();
			// The table loads on this thread while the scene lines load on the other; Apply below only picks up what is loaded.
			if (CfgTable.Value == TextSource.Off)
			{
			}
			else if (CfgTable.Value == TextSource.Revised || !File.Exists(OriginalMod.BaseTablePath))
			{
				EnsureTableRevised();
			}
			else if (!OriginalMod.Current.TableHandBack)
			{
				EnsureTableOriginal();
			}
			if (sceneThread != null)
			{
				sceneThread.Join();
				if (sceneFailure != null)
				{
					SceneError = sceneFailure.Message;
					Plugin.Log.LogError("scene text load failed: " + sceneFailure);
				}
				else if (preloaded != null)
				{
					if (preloaded.Label == "revised")
					{
						_sceneRevised = preloaded;
						NoteSceneFile(preloaded);
					}
					else
					{
						_sceneOriginal = preloaded;
						NoteSceneFile(preloaded);
					}
				}
			}
			Apply(retranslate: false);
			Plugin.Log.LogInfo($"translation ready in {sw.ElapsedMilliseconds} ms: table {TableMode}, scene {SceneMode}");
		}

		public static void SetTable(TextSource src)
		{
			if (CfgTable.Value != src)
			{
				CfgTable.Value = src;
			}
			Apply(retranslate: true);
		}

		public static void SetScene(TextSource src)
		{
			if (CfgScene.Value != src)
			{
				CfgScene.Value = src;
			}
			Apply(retranslate: true);
		}

		/// <summary>Whether Original can be shown for a layer at all, and if not, why. This mod has no copy of it: it needs the OverLlm patch.</summary>
		public static string OriginalProblem(bool table)
		{
			if (table)
			{
				if (OriginalMod.Current.TableHandBack)
				{
					return null;
				}
				if (!File.Exists(OriginalMod.BaseTablePath))
				{
					return Plugin.BaseModName + " is not installed (no Mods/English/StringTable.csv)";
				}
				return (TableFileData == BaseData.OurEdits) ? ("the table of " + Plugin.BaseModName + " holds this mod's edits from an older version; reinstall that patch") : null;
			}
			if (OriginalMod.Current.SceneHandBack)
			{
				return null;
			}
			if (!File.Exists(OriginalMod.BaseScenePath))
			{
				return Plugin.BaseModName + " is not installed (no BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt)";
			}
			return (SceneFileData == BaseData.OurEdits) ? ("the scene file of " + Plugin.BaseModName + " holds this mod's edits from an older version; reinstall that patch") : null;
		}

		/// <summary>Re-reads every translation file from disk and applies it (for edits made while the game runs).</summary>
		public static string ReloadFiles()
		{
			_tableRevised = null;
			_tableOriginal = null;
			_sceneRevised = null;
			_sceneOriginal = null;
			_tableRevisedTried = false;
			_sceneRevisedTried = false;
			TableError = null;
			SceneError = null;
			SceneText.ReloadResizersOnNextUse();
			Stopwatch sw = Stopwatch.StartNew();
			Apply(retranslate: true);
			return $"Reloaded the translation files in {sw.ElapsedMilliseconds} ms: game data text {Describe(TableMode)} ({TableEntries:N0} keys), scene text {Describe(SceneMode)} ({SceneEntries:N0} lines).";
		}

		public static string Describe(LayerMode m)
		{
			switch (m)
			{
			case LayerMode.Revised:
				return "revised";
			case LayerMode.OriginalHandBack:
				return "original (base patch)";
			case LayerMode.OriginalFromFiles:
				return "original (read from the patch's files)";
			case LayerMode.BaseOnly:
				return "base patch only";
			default:
				return "off";
			}
		}

		/// <summary>Works out both layers from the settings and the detector and installs the result; retranslate = redraw text already on screen.</summary>
		public static void Apply(bool retranslate)
		{
			if (!_started)
			{
				return;
			}
			OriginalMod.Report report = OriginalMod.Current;
			LayerMode table;
			LayerMode scene;
			try
			{
				table = ApplyTable(report);
			}
			catch (Exception ex)
			{
				Plugin.Log.LogError("game data text switch failed: " + ex);
				TableError = "switch failed: " + ex.Message;
				TextTable.Use(null);
				table = LayerMode.Off;
			}
			try
			{
				scene = ApplyScene(report);
			}
			catch (Exception ex)
			{
				Plugin.Log.LogError("scene text switch failed: " + ex);
				SceneError = "switch failed: " + ex.Message;
				SceneText.Use(null, "off", null);
				scene = LayerMode.Off;
			}
			bool tableChanged = table != TableMode;
			bool sceneChanged = scene != SceneMode;
			TableMode = table;
			SceneMode = scene;
			if (tableChanged || sceneChanged)
			{
				Plugin.Log.LogInfo($"translation: game data text {Describe(table)}, scene text {Describe(scene)}");
			}
			if (!retranslate)
			{
				return;
			}
			try
			{
				int n = SceneText.Retranslate();
				StringOverrides.Refresh();
				if (Plugin.CfgVerbose.Value)
				{
					Plugin.Log.LogInfo("translation: re-set " + n + " scene texts");
				}
			}
			catch (Exception ex)
			{
				Plugin.Log.LogWarning("translation refresh failed: " + ex.Message);
			}
		}

		private static LayerMode ApplyTable(OriginalMod.Report report)
		{
			TableOriginalProblem = null;
			if (CfgTable.Value == TextSource.Off)
			{
				TextTable.Use(null);
				return (report.BinarizerHooked && report.BinarizerEntries > 0) ? LayerMode.BaseOnly : LayerMode.Off;
			}
			if (CfgTable.Value == TextSource.Original)
			{
				if (report.TableHandBack)
				{
					TextTable.Use(null);
					_tableOriginal = null;
					return LayerMode.OriginalHandBack;
				}
				if (OriginalProblem(table: true) == null && EnsureTableOriginal() && TableFileData != BaseData.OurEdits)
				{
					TextTable.Use(_tableOriginal);
					return LayerMode.OriginalFromFiles;
				}
				TableOriginalProblem = OriginalProblem(table: true) ?? ("the table of " + Plugin.BaseModName + " could not be read: " + TableError);
			}
			if (EnsureTableRevised())
			{
				TextTable.Use(_tableRevised);
				return LayerMode.Revised;
			}
			TextTable.Use(null);
			return (report.BinarizerHooked && report.BinarizerEntries > 0) ? LayerMode.BaseOnly : LayerMode.Off;
		}

		private static LayerMode ApplyScene(OriginalMod.Report report)
		{
			SceneOriginalProblem = null;
			if (CfgScene.Value == TextSource.Off)
			{
				SceneText.Use(null, "off", null);
				return (report.XUnityRunning && report.XUnityHooked) ? LayerMode.BaseOnly : LayerMode.Off;
			}
			if (CfgScene.Value == TextSource.Original)
			{
				if (report.SceneHandBack)
				{
					SceneText.Use(null, "original (base patch)", null);
					_sceneOriginal = null;
					return LayerMode.OriginalHandBack;
				}
				if (OriginalProblem(table: false) == null && EnsureSceneOriginal() && SceneFileData != BaseData.OurEdits)
				{
					SceneText.Use(_sceneOriginal, "original (patch files)", ResizeSource(ours: false));
					return LayerMode.OriginalFromFiles;
				}
				SceneOriginalProblem = OriginalProblem(table: false) ?? ("the scene file of " + Plugin.BaseModName + " could not be read: " + SceneError);
			}
			if (EnsureSceneRevised())
			{
				SceneText.Use(_sceneRevised, "revised", ResizeSource(ours: true));
				return LayerMode.Revised;
			}
			SceneText.Use(null, "off", null);
			return (report.XUnityRunning && report.XUnityHooked) ? LayerMode.BaseOnly : LayerMode.Off;
		}

		/// <summary>The original patch's resizer files (read in its folder), then this mod's own if it has any, as SceneResizeTable.Load takes them.</summary>
		private static string ResizeSource(bool ours)
		{
			List<string> dirs = new List<string>();
			if (Directory.Exists(BaseResizeDir))
			{
				dirs.Add(BaseResizeDir);
			}
			if (ours && Directory.Exists(ResizeDir))
			{
				dirs.Add(ResizeDir);
			}
			return (dirs.Count > 0) ? string.Join(";", dirs) : null;
		}

		// ---- loading ----------------------------------------------------------------------------------------------

		private static bool EnsureTableRevised()
		{
			if (_tableRevised != null)
			{
				return true;
			}
			if (_tableRevisedTried)
			{
				return false;
			}
			_tableRevisedTried = true;
			string basePath = OriginalMod.BaseTablePath;
			bool haveBase = File.Exists(basePath);
			bool haveOwn = File.Exists(RevisedTablePath);
			if (!haveBase && !haveOwn)
			{
				TableError = "missing " + Relative(RevisedTablePath) + ", and " + Plugin.BaseModName + " is not installed";
				Plugin.Log.LogWarning("string table 'revised': " + TableError);
				return false;
			}
			if (!haveOwn)
			{
				// Not an error that stops the layer: the original patch's table alone is served.
				TableError = "missing " + Relative(RevisedTablePath) + ": only the text of " + Plugin.BaseModName + " shows";
				Plugin.Log.LogWarning("string table 'revised': " + TableError);
			}
			try
			{
				TextTable.Table t = TextTable.LoadOverlay(haveBase ? basePath : null, haveOwn ? RevisedTablePath : null, "revised", OriginalMod.TableSentinelKeys);
				TextTable.LogStats(Plugin.Log, t);
				if (t.Count == 0)
				{
					TableError = "no rows read";
					Plugin.Log.LogWarning("string table 'revised': " + TableError);
					return false;
				}
				if (haveBase)
				{
					string detail;
					TableFileData = OriginalMod.VoteSample(true, t.BaseSample, out detail);
					TableFileVote = detail;
				}
				_tableRevised = t;
				return true;
			}
			catch (Exception ex)
			{
				TableError = ex.Message;
				Plugin.Log.LogError("string table 'revised' failed: " + ex);
				return false;
			}
		}

		private static bool EnsureTableOriginal()
		{
			if (_tableOriginal != null)
			{
				return true;
			}
			string basePath = OriginalMod.BaseTablePath;
			if (!File.Exists(basePath))
			{
				return false;
			}
			_tableOriginal = LoadTable(basePath, "original");
			if (_tableOriginal != null)
			{
				_tableOriginal.BasePath = basePath;
				Dictionary<string, string> sample = new Dictionary<string, string>(StringComparer.Ordinal);
				foreach (string k in OriginalMod.TableSentinelKeys)
				{
					string v;
					if (_tableOriginal.Map.TryGetValue(k, out v))
					{
						sample[k] = v;
					}
				}
				string detail;
				TableFileData = OriginalMod.VoteSample(true, sample, out detail);
				TableFileVote = detail;
			}
			return _tableOriginal != null;
		}

		private static TextTable.Table LoadTable(string path, string label)
		{
			if (!File.Exists(path))
			{
				TableError = "missing " + Relative(path);
				Plugin.Log.LogWarning("string table '" + label + "': " + TableError);
				return null;
			}
			try
			{
				TextTable.Table t = TextTable.Load(path, label);
				TextTable.LogStats(Plugin.Log, t);
				if (t.Count == 0)
				{
					TableError = "no rows read from " + Relative(path);
					Plugin.Log.LogWarning("string table '" + label + "': " + TableError);
					return null;
				}
				return t;
			}
			catch (Exception ex)
			{
				TableError = Relative(path) + ": " + ex.Message;
				Plugin.Log.LogError("string table '" + label + "' failed: " + ex);
				return null;
			}
		}

		private static bool EnsureSceneRevised()
		{
			if (_sceneRevised != null)
			{
				return true;
			}
			if (_sceneRevisedTried)
			{
				return false;
			}
			_sceneRevisedTried = true;
			try
			{
				_sceneRevised = LoadSceneRevisedCore();
				if (_sceneRevised != null)
				{
					NoteSceneFile(_sceneRevised);
				}
			}
			catch (Exception ex)
			{
				SceneError = ex.Message;
				Plugin.Log.LogError("scene text load failed: " + ex);
			}
			return _sceneRevised != null;
		}

		private static bool EnsureSceneOriginal()
		{
			if (_sceneOriginal != null)
			{
				return true;
			}
			if (!File.Exists(OriginalMod.BaseScenePath))
			{
				return false;
			}
			try
			{
				_sceneOriginal = LoadSceneOriginalCore();
				if (_sceneOriginal != null)
				{
					NoteSceneFile(_sceneOriginal);
				}
			}
			catch (Exception ex)
			{
				SceneError = ex.Message;
				Plugin.Log.LogError("scene text (original) load failed: " + ex);
			}
			return _sceneOriginal != null;
		}

		/// <summary>The data check on the base patch's scene file as read (main thread, after a load).</summary>
		private static void NoteSceneFile(SceneDictionary d)
		{
			if (d.BaseSample.Count == 0)
			{
				return;
			}
			string detail;
			SceneFileData = OriginalMod.VoteSample(false, d.BaseSample, out detail);
			SceneFileVote = detail;
		}

		/// <summary>
		/// The original patch's XUnity file with this mod's translation/scene/*.txt (ordinal order) laid over it; without that file,
		/// this mod's lines alone. Safe on a worker thread: no Unity calls; logging goes through the thread-safe BepInEx logger.
		/// </summary>
		private static SceneDictionary LoadSceneRevisedCore()
		{
			string[] files = Directory.Exists(RevisedSceneDir) ? Directory.GetFiles(RevisedSceneDir, "*.txt", SearchOption.TopDirectoryOnly) : new string[0];
			Array.Sort(files, StringComparer.Ordinal);
			string basePath = OriginalMod.BaseScenePath;
			bool haveBase = File.Exists(basePath);
			if (files.Length == 0 && !haveBase)
			{
				SceneError = "no *.txt files in " + Relative(RevisedSceneDir) + ", and " + Plugin.BaseModName + " is not installed";
				Plugin.Log.LogWarning("scene text 'revised': " + SceneError);
				return null;
			}
			if (files.Length == 0)
			{
				SceneError = "no *.txt files in " + Relative(RevisedSceneDir) + ": only the lines of " + Plugin.BaseModName + " show";
				Plugin.Log.LogWarning("scene text 'revised': " + SceneError);
			}
			Stopwatch sw = Stopwatch.StartNew();
			SceneDictionary d = SceneDictionary.LoadOverlay(haveBase ? basePath : null, files, OriginalMod.SceneSentinelKeys.ToList());
			d.Label = "revised";
			Plugin.Log.LogInfo($"scene text 'revised': " + (haveBase ? $"the original patch's file ({Relative(basePath)})" : "no original patch file (not installed)") + $" with this mod's {d.OverlayEntries} lines over it ({d.Substituted} replaced, {d.Removed} removed, {d.Added} added)");
			return Finish(d, "revised", sw);
		}

		/// <summary>The original patch's own XUnity file, as XUnity would read it.</summary>
		private static SceneDictionary LoadSceneOriginalCore()
		{
			Stopwatch sw = Stopwatch.StartNew();
			string basePath = OriginalMod.BaseScenePath;
			SceneDictionary d = SceneDictionary.LoadOverlay(basePath, new string[0], OriginalMod.SceneSentinelKeys.ToList());
			d.Label = "original";
			return Finish(d, "original", sw);
		}

		private static SceneDictionary Finish(SceneDictionary d, string label, Stopwatch sw)
		{
			Plugin.Log.LogInfo($"scene text '{label}': {d.Entries} lines from {d.Files.Count} file(s) in {sw.ElapsedMilliseconds} ms ({d.KeyCount} keys with whitespace variants, {d.RegexCount} regex, {d.Rejected} rejected, {d.Empty} empty, {d.Duplicates} duplicates)");
			foreach (string w in d.Warnings.Take(20))
			{
				Plugin.Log.LogInfo("  " + w);
			}
			if (d.Entries == 0)
			{
				SceneError = "no lines read (" + label + ")";
				return null;
			}
			return d;
		}

		private static string Relative(string path)
		{
			try
			{
				string root = Paths.GameRootPath.TrimEnd('\\', '/') + Path.DirectorySeparatorChar;
				return path.StartsWith(root, StringComparison.OrdinalIgnoreCase) ? path.Substring(root.Length).Replace('\\', '/') : path;
			}
			catch (Exception)
			{
				return path;
			}
		}
	}
}
