"""One-time cut-over of LOM_UI_EN to the revisions-only layout (0.5, "overlay-1"): the plugin folder keeps only this mod's own
work, the full working tables and the rules with their comments move to LOM_Localization/workspace, the OverLlm release they
diverged from to LOM_Localization/base_ref (see lom_paths.py and publish.py).

  python cutover_0_5.py --stage DIR [--replace-stage] [--dll PATH]
        dry run: copies today's plugin folder to DIR/plugin (with PATH as its LOM_UI_EN.dll when given: the 0.5 build that
        will be installed, e.g. LOM_Localization/src/LOM_UI_EN/bin/LOM_UI_EN.dll) and does every step below with DIR/plugin,
        DIR/workspace, DIR/base_ref and DIR/backups. The real folders are only read.
  python cutover_0_5.py --live
        the real cut-over, on BepInEx/plugins/LOM_UI_EN, LOM_Localization/workspace, LOM_Localization/base_ref and
        LOM_Localization/backups. Install LOM_UI_EN 0.5.0 or later first: the cut-over refuses an older plugin DLL.
  python cutover_0_5.py --rollback BACKUP_DIR
        undoes a cut-over (the real layout; LOM_STAGE=DIR for a staged one): translation/, strings/, profiles/ and rules/
        come back from BACKUP_DIR (backups/pre-0.5-<stamp>) exactly, the files the cut-over added go, and the workspace and
        base_ref move to backups/rolled-back-<stamp>/. The cut-over can then run again.

Steps
  1. preflight, before anything is written: refuse if Mortal.exe is running (or that cannot be told), if the plugin DLL is
     older than 0.5.0, if the workspace or base_ref exist already, if the plugin folder was published into before
     (translation/.publish_state.json: roll that cut-over back first), or if the folder does not hold the 0.4 layout (full
     translation/StringTable.csv and scene/scene_text.txt, a 0.4 MANIFEST.json, profiles/original with the release's
     md5s, rules/). Then the whole cut-over runs in memory: the workspace with its data fixes, base_ref, the publish plan,
     its check, and the plugin-folder conflict and removal checks. Any refusal stops here, with nothing written.
  2. back up translation/ (MANIFEST.json, scene/resize and untranslated.txt included), strings/, profiles/ and rules/ to
     backups/pre-0.5-<stamp>/ with hashes.json (which also lists the files the cut-over adds), and check the copies
  3. WORKSPACE := translation/StringTable.csv, translation/scene/scene_text.txt, strings/*.csv and rules/*.json as the
     plugin has them, sentinels.json (the 24+24 MANIFEST sentinel keys with SHA-1 hashes, no text) and README.txt, with these
     data fixes applied (logged to backups/pre-0.5-<stamp>/datafix.tsv and LOM_Localization/cutover_0_5/; the backup holds
     the files before them):
       - scene lines that are XUnity's own runtime (Google) lines go: in the installed OverLlm XUnity file byte for byte, not
         in the release, not revised by this mod
       - wording overrides whose text is OverLlm's line for the key go when they change nothing (our table row has the same
         text) or are longer than 3 words; a short label that changes what the player sees stays; each decision is logged
       - wording overrides whose text holds a literal "[...]" / "[...unchanged...]" placeholder go, so the table text shows;
         their keys are listed for re-translation (retranslate.<stamp>.txt)
  4. BASE_REF := profiles/original/StringTable.csv and xunity_translations.txt (as _AutoGeneratedTranslations.txt), the 0.4
     copies of the release's resizers (resize/), README.txt, base_ref.json; then workspace/base_ref.lock
  5. publish.py build into the plugin folder (it replaces the 0.4 files, which the backup and the workspace hold, and removes
     translation/scene/resize and profiles/), then publish.py check
  6. summary: counts, sizes before and after, the backup, how to roll back
"""
import argparse, datetime, json, os, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)
import lom_paths as P
import publish as PB

EXPECT = {
    "profiles/original/StringTable.csv": "c9e1292a4a8f3e8b27d8bb01ba9563d4",
    "profiles/original/xunity_translations.txt": "88b0afa4053e06bb5ca836b6dc001308",
}
RELEASE = ("OverLlm EnglishPatch (github.com/joshfreitas1984/LegendOfMortalOverLlm): StringTable.csv = the release's "
           "Mods/English/StringTable.csv dated 2026-02-06 (md5 c9e1292a4a8f3e8b27d8bb01ba9563d4); _AutoGeneratedTranslations.txt "
           "= the release's XUnity file plus the 113 lines XUnity's Google fallback appended while playing before this mod's "
           "edits (md5 88b0afa4053e06bb5ca836b6dc001308), as kept in LOM_UI_EN 0.4's profiles/original")
STAGE_MARK = ".lom_cutover_stage"
BACKUP_DIRS = ("translation", "strings", "profiles", "rules")
ADDED_FILES = ("THIRD_PARTY_NOTICES.txt",)      # top-level files the cut-over's publish may add (removed by --rollback)
BS = chr(92)


def say(*a):
    print(*a, flush=True)


def tree_size(path):
    n = 0
    for root, dirs, files in os.walk(path):
        for f in files:
            n += os.path.getsize(os.path.join(root, f))
    return n


def sizes(plugin):
    out = {"plugin folder": tree_size(plugin)}
    for rel in ("translation", "profiles", "strings", "rules", "translation/StringTable.csv", "translation/StringTable.meta.tsv",
                "translation/scene/scene_text.txt", "translation/scene/resize", "translation/MANIFEST.json"):
        p = PB.rel_path(plugin, rel)
        if os.path.isdir(p):
            out[rel] = tree_size(p)
        elif os.path.exists(p):
            out[rel] = os.path.getsize(p)
    return out


def fmt(n):
    return "%.2f MB" % (n / 1048576.0) if n >= 1 << 20 else "%.1f KB" % (n / 1024.0)


def hashes_of(root):
    out = {}
    for r, dirs, files in os.walk(root):
        for f in files:
            p = os.path.join(r, f)
            out[os.path.relpath(p, root).replace(os.sep, "/")] = {"md5": PB.md5_file(p), "size": os.path.getsize(p)}
    return out


def tsv(s):
    return str(s).replace(BS, BS + BS).replace("\t", BS + "t").replace("\r", BS + "r").replace("\n", BS + "n")


def dll_problem(plugin):
    dll = os.path.join(plugin, "LOM_UI_EN.dll")
    v = PB.plugin_version(dll)
    if v is None:
        return "%s is missing or holds no LOM_UI_EN version" % dll
    if PB.version_tuple(v) < PB.MIN_PLUGIN_VERSION:
        return ("the plugin DLL is LOM_UI_EN %s; the 0.5 layout needs %s or later (it reads the revisions-only files). Install the "
                "0.5 build first%s" % (v, ".".join(map(str, PB.MIN_PLUGIN_VERSION)),
                                       "" if P.STAGE is None else " (for a stage run: --dll %s)" % P.PLUGIN_BUILD_DLL))
    return None


def make_sentinels(manifest, base_tt, ws_tt, base_sc, ws_sc):
    """sentinels.json: the MANIFEST keys with hashes of today's plain values, checked against the files they came from."""
    out, report = {"note": "Sentinel keys for the plugin's check of what the installed OverLlm patch's files hold: "
                           "original_sha1 / revised_sha1 = first 16 hex digits of SHA-1 over the UTF-8 English of the OverLlm "
                           "release / of this mod's pre-0.4 edit of the patch's files (LOM_UI_EN 0.4 MANIFEST.json). No text.",
                   "table": [], "scene": []}, {}
    for layer, base, ws in (("table", base_tt, ws_tt), ("scene", base_sc, ws_sc)):
        orig_ok = rev_now = 0
        for s in manifest[layer + "_sentinels"]:
            k = s["key"]
            if base.get(k) != s["original"]:
                sys.exit("cut-over refused: MANIFEST %s sentinel %r: its original English is not the release's" % (layer, k))
            orig_ok += 1
            rev_now += ws.get(k) == s["revised"]
            out[layer].append({"key": k, "original_sha1": PB.text_hash(s["original"]), "revised_sha1": PB.text_hash(s["revised"])})
        report[layer] = "%s: %d sentinels, original = the release's English for all %d, revised = today's English for %d" % (
            layer, len(out[layer]), orig_ok, rev_now)
    return out, report


def virtual_workspace(plugin, manifest):
    """The workspace and BASE_REF the cut-over will write, in memory (the data fixes applied), as publish.Inputs takes them."""
    rb = lambda rel: PB.file_bytes(PB.rel_path(plugin, rel))
    table = rb("translation/StringTable.csv")
    scene0 = rb("translation/scene/scene_text.txt")
    base_table = rb("profiles/original/StringTable.csv")
    base_scene = rb("profiles/original/xunity_translations.txt")
    sd, rd = PB.rel_path(plugin, "strings"), PB.rel_path(plugin, "rules")
    strings0 = PB._read_dir(sd, lambda f: f.lower().endswith(".csv"))
    rules = PB._read_dir(rd, lambda f: f.lower().endswith(".json"))
    ws_tt, _ = PB.table_map(PB._text(table))
    base_tt, _ = PB.table_map(PB._text(base_table))
    ws_sf, base_sf = PB.SceneFile(data=scene0, label="0.4 scene file"), PB.SceneFile(data=base_scene, label="release scene file")
    inst_sf = PB.SceneFile(P.BASE_SCENE) if os.path.exists(P.BASE_SCENE) else None
    sentinels, srep = make_sentinels(manifest, base_tt, ws_tt, base_sf.map, ws_sf.map)
    scene1, drops = PB.datafix_scene_runtime_lines(ws_sf, base_sf, inst_sf)
    scene = scene1 if scene1 is not None else scene0
    strings, decisions = PB.datafix_overrides(strings0, base_tt, ws_tt)
    # the 0.4 resize folder holds copies of the release's resizers (to base_ref/resize); anything else there is this mod's own
    base_resize_src, own_resize = {}, {}
    rz = PB.rel_path(plugin, "translation/scene/resize")
    if os.path.isdir(rz):
        for f in sorted(os.listdir(rz)):
            p = os.path.join(rz, f)
            if not PB._is_resizer(f) or os.path.isdir(p):
                continue
            inst = os.path.join(P.BASE_RESIZE_DIR, f)
            if not os.path.exists(P.BASE_RESIZE_DIR) or (os.path.exists(inst) and PB.md5_file(inst) == PB.md5_file(p)):
                base_resize_src[f] = p
            else:
                own_resize[f] = PB.file_bytes(p)
    mem = {"table": table, "scene": scene, "strings": strings, "rules": rules, "resize": own_resize,
           "base_table": base_table, "base_scene": base_scene, "sentinels": sentinels, "base_info": {"release": RELEASE},
           "base_resize": {f: PB.file_bytes(p) for f, p in base_resize_src.items()}, "game_source": None}
    return {"mem": mem, "scene_drops": drops, "override_decisions": decisions, "sentinel_report": srep,
            "base_resize_src": base_resize_src}


def preflight(plugin):
    if PB.game_running():
        sys.exit(PB.GAME_RUNNING_MSG)
    problems = []
    for p in (P.WORKSPACE, P.BASE_REF):
        if os.path.exists(p) and os.listdir(p):
            problems.append("%s exists already: the cut-over has been done (or started) before" % p)
    if os.path.exists(PB.rel_path(plugin, PB.REL_STATE)):
        problems.append("%s exists: this plugin folder was published into (a cut-over ran here). Roll that back first: python "
                        "cutover_0_5.py --rollback <its backups/pre-0.5-<stamp> folder>" % PB.REL_STATE)
    need = ["translation/StringTable.csv", "translation/scene/scene_text.txt", "translation/MANIFEST.json", "strings", "rules",
            "profiles/original/StringTable.csv", "profiles/original/xunity_translations.txt"]
    for rel in need:
        if not os.path.exists(PB.rel_path(plugin, rel)):
            problems.append("%s is missing" % rel)
    d = dll_problem(plugin)
    if d:
        problems.append(d)
    if problems:
        sys.exit("cut-over refused:\n  " + "\n  ".join(problems))
    for rel, want in EXPECT.items():
        got = PB.md5_file(PB.rel_path(plugin, rel))
        if got != want:
            problems.append("%s md5 %s, expected %s (the release copy)" % (rel, got, want))
    with open(PB.rel_path(plugin, "translation/MANIFEST.json"), encoding="utf-8") as f:
        manifest = json.load(f)
    if manifest.get("format") == PB.FORMAT:
        problems.append("translation/MANIFEST.json is already format %s" % PB.FORMAT)
    for layer in ("table", "scene"):
        ss = manifest.get(layer + "_sentinels") or []
        if not ss or any(not ({"key", "revised", "original"} <= set(s)) for s in ss):
            problems.append("MANIFEST.json %s_sentinels are not the 0.4 {key, revised, original} entries" % layer)
    tt, _ = PB.table_map(PB.read_text(PB.rel_path(plugin, "translation/StringTable.csv")))
    base, _ = PB.table_map(PB.read_text(PB.rel_path(plugin, "profiles/original/StringTable.csv")))
    if len(tt) < len(base):
        problems.append("translation/StringTable.csv has %d keys, the release %d: not the full 0.4 table" % (len(tt), len(base)))
    for sub in ("strings", "rules"):
        dd = PB.rel_path(plugin, sub)
        if os.path.isdir(dd) and any(os.path.isdir(os.path.join(dd, f)) for f in os.listdir(dd)):
            problems.append("%s/ holds folders; the workspace takes only the files directly in it" % sub)
    if problems:
        sys.exit("cut-over refused:\n  " + "\n  ".join(problems))
    # the whole cut-over, in memory: any refusal of the publish or its check happens here, before a single write
    try:
        PB._guard_target(plugin)
        virt = virtual_workspace(plugin, manifest)
        inp = PB.Inputs(mem=virt["mem"])
        plan, rep = PB.make_plan(inp)
        probs, info = PB.verify(inp, plan)
        if probs:
            sys.exit("cut-over refused (nothing written): the publish would fail its check:\n  " + "\n  ".join(probs[:20]))
        ops = PB.plan_ops(plugin, plan, inp, adopt=True)
        if ops["conflicts"]:
            sys.exit("cut-over refused (nothing written): the plugin folder holds files the publish would neither replace nor "
                     "remove:\n  " + "\n  ".join("%s: %s" % c for c in ops["conflicts"]))
    except PB.PublishError as e:
        sys.exit("cut-over refused (nothing written): %s" % e)
    say("preflight: the cut-over runs clean in memory (table %d rows, scene %d lines + %d removals, %d files to write, %d to "
        "remove, %d data fixes)" % (rep["table_rows"], rep["scene_lines"], rep["scene_tombstones"], len(ops["writes"]),
                                    len(ops["removes"]), len(virt["scene_drops"]) + len(virt["override_decisions"])))
    return manifest, virt


def write_datafix_logs(stamp, bdir, virt):
    rows = [("fix", "file", "where", "action", "why", "text")]
    for n, k, v in virt["scene_drops"]:
        rows.append(("xunity_runtime_line", "translation/scene/scene_text.txt", "line %d: %s" % (n, k), "delete",
                     "XUnity's own runtime (Google) line: in the installed OverLlm file, not in the release, not revised", v))
    retrans = []
    for f, k, action, why, t in virt["override_decisions"]:
        kind = "placeholder_override" if "placeholder" in why else "override_equals_overllm"
        rows.append((kind, "strings/" + f, k, action, why, t))
        if kind == "placeholder_override":
            retrans.append("%s\tstrings/%s" % (k, f))
    body = "".join("\t".join(tsv(x) for x in r) + "\n" for r in rows)
    logdir = P.log_dir("cutover_0_5")          # LOCALIZATION/cutover_0_5, guarded (no junction or link out of it)
    paths = []
    for d, name in ((bdir, "datafix.tsv"), (logdir, "datafix.%s.tsv" % stamp)):
        with open(P.out_path(d, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(body)
        paths.append(os.path.join(d, name))
    rt = "# wording overrides deleted because their text was a '[...]' placeholder: re-translate these keys\n" + "".join(x + "\n" for x in retrans)
    for d, name in ((bdir, "retranslate.txt"), (logdir, "retranslate.%s.txt" % stamp)):
        with open(P.out_path(d, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(rt)
        paths.append(os.path.join(d, name))
    return paths, len(retrans)


def run(plugin, live):
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    say("cut-over %s: plugin %s\n  workspace %s\n  base_ref  %s\n  backups   %s" % (
        "LIVE" if live else "STAGED", plugin, P.WORKSPACE, P.BASE_REF, P.BACKUPS))
    manifest, virt = preflight(plugin)
    mem = virt["mem"]
    before = sizes(plugin)

    # 2. backup
    for p in (P.WORKSPACE, P.BASE_REF):
        P.guard_write(p)
    P.guard_under(os.path.join(P.LOCALIZATION, "cutover_0_5"), P.LOCALIZATION)
    bdir = P.new_backup_dir("pre-0.5", stamp)      # guarded: inside BACKUPS, no junction or link out of it
    for rel in BACKUP_DIRS:
        if os.path.isdir(PB.rel_path(plugin, rel)):
            shutil.copytree(PB.rel_path(plugin, rel), P.out_path(bdir, rel))
    shutil.copy2(PB.rel_path(plugin, "translation/MANIFEST.json"), P.out_path(bdir, "MANIFEST.json"))
    h = {rel: hashes_of(PB.rel_path(plugin, rel)) for rel in BACKUP_DIRS if os.path.isdir(PB.rel_path(plugin, rel))}
    for rel, files in h.items():
        got = hashes_of(os.path.join(bdir, rel))
        if got != files:
            sys.exit("backup check failed for %s; nothing else was done (backup at %s)" % (rel, bdir))
    absent = [f for f in ADDED_FILES if not os.path.exists(os.path.join(plugin, f))]
    with open(P.out_path(bdir, "hashes.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump({"from": plugin, "created": stamp, "folders": h, "absent": absent}, f, indent=1, ensure_ascii=False)
    say("backup    ->", bdir, "(%d files, checked)" % sum(len(v) for v in h.values()))

    # 3. workspace (what the preflight ran in memory, byte for byte)
    for d in (P.SCENE_DIR, P.STRINGS_DIR, P.WS_RULES_DIR):
        os.makedirs(d, exist_ok=True)
    out = [(P.TABLE, mem["table"]), (P.SCENE, mem["scene"])]
    out += [(os.path.join(P.STRINGS_DIR, n), b) for n, b in mem["strings"].items()]
    out += [(os.path.join(P.WS_RULES_DIR, n), b) for n, b in mem["rules"].items()]
    if mem["resize"]:
        os.makedirs(P.WS_RESIZE_DIR, exist_ok=True)
        out += [(os.path.join(P.WS_RESIZE_DIR, n), b) for n, b in mem["resize"].items()]
    for dst, data in out:
        with open(dst, "wb") as f:
            f.write(data)
        if PB.md5_file(dst) != PB.md5_bytes(data):
            sys.exit("workspace write of %s failed the read-back" % dst)
    with open(P.WS_SENTINELS, "w", encoding="utf-8", newline="\n") as f:
        json.dump(mem["sentinels"], f, indent=1, ensure_ascii=False)
    with open(os.path.join(P.WORKSPACE, "README.txt"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write("LOM_UI_EN maintainer workspace (never shipped)\n\n"
                "  translation/StringTable.csv       the full working string table (lom_paths.TABLE)\n"
                "  translation/scene/scene_text.txt  the full working scene file (lom_paths.SCENE)\n"
                "  translation/scene/resize/         this mod's own *.resizer.txt, if any (shipped as they are)\n"
                "  strings/*.csv                     wording overrides with their full review notes (lom_paths.STRINGS_DIR)\n"
                "  rules/*.json                      layout rules with their comments (shipped without them)\n"
                "  sentinels.json                    the data-check sentinel keys (hashes only)\n"
                "  base_ref.lock                     the base_ref release this workspace is aligned with (do not edit)\n"
                "  translation/revision_record.tsv   per revised table row, the hashes of the game text and of the OverLlm\n"
                "                                    line it was revised against (publish.py keeps it; do not edit)\n\n"
                "Every tool in LOM_Localization/tools edits these files. The plugin folder gets only the difference from the\n"
                "OverLlm release in LOM_Localization/base_ref: run python LOM_Localization/tools/publish.py build after editing\n"
                "(the apply tools do it themselves). These files hold the OverLlm patch's text too: never ship them.\n")
    logs, nretrans = write_datafix_logs(stamp, bdir, virt)
    kept = [d for d in virt["override_decisions"] if d[2] == "keep"]
    say("workspace ->", P.WORKSPACE, "(%d files; %s; %s)" % (len(out) + 2, virt["sentinel_report"]["table"],
                                                            virt["sentinel_report"]["scene"]))
    say("data fixes: %d XUnity runtime scene lines removed; %d overrides equal to OverLlm's line removed, %d kept; %d placeholder "
        "overrides removed (keys for re-translation: %s)" % (
            len(virt["scene_drops"]), sum(1 for d in virt["override_decisions"] if d[2] == "delete" and "placeholder" not in d[3]),
            len(kept), nretrans, logs[3]))
    for f, k, action, why, t in virt["override_decisions"]:
        if "placeholder" not in why:
            say("    %-6s strings/%s %s: %s" % (action, f, k, why))
    say("  logs:", logs[1], "(and", logs[0] + ")")

    # 4. base_ref, then the lock that ties the workspace to it
    PB.write_base_ref(PB.rel_path(plugin, "profiles/original/StringTable.csv"),
                      PB.rel_path(plugin, "profiles/original/xunity_translations.txt"),
                      "cut-over 0.5 (%s) from %s" % (stamp, PB.rel_path(plugin, "profiles/original")), release=RELEASE,
                      resize=virt["base_resize_src"])
    for rel, dst in (("profiles/original/StringTable.csv", P.BASE_REF_TABLE), ("profiles/original/xunity_translations.txt", P.BASE_REF_SCENE)):
        if PB.md5_file(dst) != EXPECT[rel]:
            sys.exit("BASE_REF copy of %s differs" % rel)
    PB.write_lock(P.WS_LOCK, PB.lock_data(PB.file_bytes(P.BASE_REF_TABLE), PB.file_bytes(P.BASE_REF_SCENE)))
    say("base_ref  ->", P.BASE_REF, "(+ %d resizers; lock %s)" % (len(virt["base_resize_src"]), P.WS_LOCK))

    # 5. publish + check
    rollback_cmd = "python %s --rollback %s%s" % (os.path.join(P.TOOLS, "cutover_0_5.py"), bdir,
                                                  "" if live else "   (with LOM_STAGE=%s)" % P.STAGE)
    try:
        res = PB.build(plugin, adopt=True, verbose=True, rerecord=True)   # the first record of every shipped row
    except PB.PublishError as e:
        say("PUBLISH FAILED: %s" % e)
        say("roll back with: %s" % rollback_cmd)
        sys.exit(1)
    probs, info = PB.check(plugin)
    say("check:")
    for k, v in info.items():
        say("  %-44s %s" % (k, v))
    for p in probs:
        say("FAIL:", p)
    after = sizes(plugin)

    # 6. summary
    rep = res["report"]
    say("\nsummary")
    say("  table   %d rows shipped (%d revised, %d added) of %d workspace keys; revision record %d rows (%d with the game's "
        "text hash)" % (rep["table_rows"], rep["table_revised"], rep["table_added"], len(PB.table_map(PB.read_text(P.TABLE))[0]),
                        rep["meta"]["rows"], rep["meta"]["with_game_text"]))
    say("  scene   %d lines shipped (%d revised, %d added) + %d removal lines + %d trimmed-variant lines" % (
        rep["scene_lines"], rep["scene_revised"], rep["scene_added"], rep["scene_tombstones"], rep["scene_variant_lines"]))
    s = rep["strings"]
    say("  strings %d files, %d of %d notes cleaned (%d emptied), %d comment rows left out" % (
        s["files"], s["cleaned"], s["notes"], s["emptied"], len(s["dropped_comments"])))
    r = rep["rules"]
    say("  rules   %d files, %d rules; %d '//' comments and %d comment fields removed%s" % (
        r["files"], r["rules"], r["comments"], r["comment_fields"],
        ("; other fields the loader ignores removed: %s" % r["other_removed"][:5]) if r["other_removed"] else ""))
    say("  sentinels kept: table %d, scene %d (dropped: %s)" % (
        rep["sentinels"]["table"]["kept"], rep["sentinels"]["scene"]["kept"],
        rep["sentinels"]["table"]["dropped"] + rep["sentinels"]["scene"]["dropped"] or "none"))
    say("  removed: %s" % (", ".join(res["removed"]) or "nothing"))
    say("  sizes (before -> after):")
    for k in before:
        say("    %-36s %10s -> %s" % (k, fmt(before[k]), fmt(after[k]) if k in after else "removed"))
    for k in after:
        if k not in before:
            say("    %-36s %10s -> %s" % (k, "-", fmt(after[k])))
    say("  backup: %s" % bdir)
    say("  roll back: %s" % rollback_cmd)
    say("check %s" % ("FAILED" if probs else "ok"))
    return 1 if probs else 0


def rollback(bdir):
    """Undo a cut-over from its backup: the backed-up folders back exactly, the files it added gone, workspace and base_ref
    moved aside (nothing is deleted)."""
    if PB.game_running():
        sys.exit(PB.GAME_RUNNING_MSG)
    bdir = os.path.abspath(bdir)
    hp = os.path.join(bdir, "hashes.json")
    if not os.path.exists(hp):
        sys.exit("%s has no hashes.json: not a cut-over backup" % bdir)
    with open(hp, encoding="utf-8") as f:
        h = json.load(f)
    plugin = P.PLUGIN
    if not P.same_path(h.get("from", "") or "?", plugin):
        sys.exit("the backup is of %s, not of %s (LOM_STAGE=<stage root> for a staged cut-over)" % (h.get("from"), plugin))
    for rel, files in h["folders"].items():
        if hashes_of(os.path.join(bdir, rel)) != files:
            sys.exit("backup folder %s does not match its hashes.json; nothing was changed" % rel)
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    aside = P.new_backup_dir("rolled-back", stamp)
    os.makedirs(P.out_path(aside, "plugin"))
    unt = PB.rel_path(plugin, PB.REL_UNTRANSLATED)
    untranslated = PB.file_bytes(unt) if os.path.exists(unt) else None     # written by the game since: keep it
    for rel in h["folders"]:
        p = PB.rel_path(plugin, rel)
        if os.path.exists(p):
            shutil.move(p, os.path.join(aside, "plugin", rel))
    for f in h.get("absent", []):
        p = os.path.join(plugin, f)
        if os.path.exists(p):
            shutil.move(p, os.path.join(aside, "plugin", f))
    for rel in h["folders"]:
        shutil.copytree(os.path.join(bdir, rel), PB.rel_path(plugin, rel))
        if hashes_of(PB.rel_path(plugin, rel)) != h["folders"][rel]:
            sys.exit("restore of %s failed its hash check (the files before the roll-back are in %s)" % (rel, aside))
    if untranslated is not None:
        with open(unt, "wb") as f:
            f.write(untranslated)
    moved = []
    for d in (P.WORKSPACE, P.BASE_REF):
        if os.path.exists(d):
            shutil.move(d, os.path.join(aside, os.path.basename(d)))
            moved.append(d)
    say("rolled back %s from %s: %s restored; removed %s; moved aside to %s: the replaced files, %s" % (
        plugin, bdir, ", ".join(h["folders"]), [f for f in h.get("absent", [])] or "nothing", aside, ", ".join(moved) or "-"))
    say("the cut-over can run again")
    return 0


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--stage", help="dry run into this folder (a copy of the plugin folder is made there)")
    g.add_argument("--live", action="store_true", help="the real cut-over")
    g.add_argument("--rollback", metavar="BACKUP_DIR", help="undo a cut-over from its backups/pre-0.5-<stamp> folder")
    ap.add_argument("--replace-stage", action="store_true", help="delete an earlier --stage run in the same folder first")
    ap.add_argument("--dll", help="--stage only: put this LOM_UI_EN.dll into the staged plugin copy (the build to install)")
    a = ap.parse_args()
    if a.rollback:
        return rollback(a.rollback)
    if PB.game_running():
        sys.exit(PB.GAME_RUNNING_MSG)
    if a.live:
        if P.STAGE:
            sys.exit("LOM_STAGE is set (%s); unset it for the live cut-over" % P.STAGE)
        if a.dll or a.replace_stage:
            sys.exit("--dll and --replace-stage are for --stage runs; install the 0.5 DLL into the plugin folder yourself")
        return run(P.PLUGIN, live=True)
    if P.STAGE:
        sys.exit("LOM_STAGE is set (%s); unset it for a --stage run (the stage folder comes from --stage)" % P.STAGE)
    real_plugin = P.PLUGIN
    root = os.path.abspath(a.stage)
    try:
        P.stage(root)
    except ValueError as e:
        sys.exit(str(e))
    if a.dll and not os.path.exists(a.dll):
        sys.exit("%s does not exist" % a.dll)
    if os.path.exists(root) and os.listdir(root):
        if not (a.replace_stage and os.path.exists(os.path.join(root, STAGE_MARK))):
            sys.exit("%s is not empty (pass --replace-stage to replace an earlier staged run there)" % root)
        PB._rmtree(root)
    os.makedirs(root, exist_ok=True)
    with open(os.path.join(root, STAGE_MARK), "w") as f:
        f.write("staged cut-over; safe to delete\n")
    shutil.copytree(real_plugin, P.PLUGIN)
    say("staged a copy of %s at %s" % (real_plugin, P.PLUGIN))
    if a.dll:
        shutil.copy2(a.dll, os.path.join(P.PLUGIN, "LOM_UI_EN.dll"))
        say("staged plugin DLL <- %s (LOM_UI_EN %s)" % (a.dll, PB.plugin_version(a.dll)))
    return run(P.PLUGIN, live=False)


if __name__ == "__main__":
    sys.exit(main())
