"""Where the Legend of Mortal English text lives (LOM_UI_EN 0.5 and later: the revisions-only "overlay-1" layout).

Every tool that reads or writes translation data imports its paths from here, so the data can move without editing each
script. Three places, only one of which is shipped:

  WORKSPACE  LOM_Localization/workspace/            maintainer only, never shipped
             translation/StringTable.csv              the full working string table   (TABLE)
             translation/scene/scene_text.txt         the full working scene file     (SCENE)
             translation/scene/resize/*.resizer.txt   this mod's own resizers, if any (WS_RESIZE_DIR)
             strings/*.csv                            wording overrides with full notes (STRINGS_DIR)
             rules/*.json                             layout rules with their comments (WS_RULES_DIR)
             sentinels.json                           the data-check sentinel keys (hashes only)
             base_ref.lock                            md5s of the BASE_REF files this workspace is aligned with (WS_LOCK)
             nametips.tsv                             dialog name tips: character ids, extra name forms, portrait crops
                                                      (WS_NAMETIPS; tools/nametips/nametips.py; shipped byte for byte)
             factiontips.tsv                          faction tips: id, title, forms, this mod's spoiler-free description
                                                      (WS_FACTIONTIPS; the same tool; shipped byte for byte)
             translation/revision_record.tsv          per revised table row, the hashes of the game text and of the OverLlm
                                                      line it was revised against, kept from when it was revised (WS_RECORD;
                                                      written by publish.py only)
             translation/reviewed.tsv                 the review ledger: table keys a line-by-line review pass reviewed
                                                      (WS_LEDGER; key TAB pass TAB date, written through ledger.py)
             translation/scene/reviewed_scene.tsv     the same for scene lines, by their raw XUnity key as written in the
                                                      scene file, and 'resize/<file>' for this mod's own resizers
                                                      (WS_SCENE_LEDGER). A reviewed line ships even when its text is OverLlm's
  BASE_REF   LOM_Localization/base_ref/             maintainer only, never shipped: the OverLlm release the workspace
             StringTable.csv                          diverged from (BASE_REF_TABLE, BASE_REF_SCENE)
             _AutoGeneratedTranslations.txt
             resize/*.resizer.txt                     the release's resizers (to tell ours from theirs)
             game_source.tsv                          the game's own Chinese per key (a harness 'srcdump'; BASE_REF_SOURCE)
             history/NN-<stamp>/                      each earlier release the workspace was aligned with (kept by rebase;
                                                      BASE_REF_HISTORY), so its wording is still known as OverLlm's
  PLUGIN     BepInEx/plugins/LOM_UI_EN/              what players get: only this mod's own work
             translation/StringTable.csv              rows whose value differs from BASE_REF, or that the ledger lists (SHIP_TABLE)
             translation/StringTable.meta.tsv         per shipped row: hashes of the game text and of BASE_REF's line
             translation/scene/scene_text.txt         lines whose value differs or that the ledger lists, plus "key=" removals
                                                      (SHIP_SCENE)
             translation/scene/resize/*.resizer.txt   this mod's own resizers (copied from the workspace; a reviewed copy of
                                                      OverLlm's ships too when the scene ledger lists it)
             translation/MANIFEST.json                hashes only (SHIP_MANIFEST)
             strings/*.csv                            the overrides with notes stripped of quoted wording (SHIP_STRINGS_DIR)
             rules/*.json                             the rules without comments (SHIP_RULES_DIR)

Every editing tool reads and writes the WORKSPACE (TABLE / SCENE / STRINGS_DIR hold the full tables, so the tools work as
before) and calls publish() after a live write; publish.py derives the PLUGIN files from WORKSPACE minus BASE_REF. The
original OverLlm patch's installed files (BASE_TABLE, BASE_SCENE, BASE_RESIZE_DIR) belong to that patch and are only read.

Staging: stage(root) (or the environment variable LOM_STAGE=root, read at import) moves PLUGIN, WORKSPACE, BASE_REF, BACKUPS
and LOCALIZATION (the tools' change logs and their non-live output) under root/plugin, root/workspace, root/base_ref,
root/backups and root/localization, so a dry run never touches the real folders. TOOLS, PLUGIN_SRC and NOTICES_SRC stay the
real ones (read only). A staging root may not be, hold or sit inside the game folder or LOM_Localization.

Every guard here (inside, same_path, stage, assert_writable, assert_ledger_writable, guard_write, guard_under) resolves
paths first (os.path.realpath, plus os.path.samefile where both exist), so an 8.3 short name (C:/PROGRA~2/...), a junction or
a symbolic link cannot pass for another folder. The tools' output folders come from here and are checked the same way before
anything is written into them: log_dir(name) (a --live change log, LOCALIZATION/<name>), staged_dir(name) (non-live output),
backup_path / new_backup_dir (BACKUPS) and out_path(folder, name) for each file written into one of them; a junction or link
anywhere on the way (or a '..' in a name) that would carry the write out of its folder is refused.
"""
import os
import sys

# The game folder: the LOM_GAME environment variable (as for src/LOM_UI_EN/build.ps1), else the default Steam folder.
GAME = os.environ.get("LOM_GAME") or r"C:\Program Files (x86)\Steam\steamapps\common\LegendOfMortal"
REAL_LOCALIZATION = os.path.join(GAME, "LOM_Localization")
TOOLS = os.path.join(REAL_LOCALIZATION, "tools")

# The original patch's own installed files (read only; publish.py and the plugin read them, nothing here writes them).
BASE_TABLE = os.path.join(GAME, "Mods", "English", "StringTable.csv")
BASE_SCENE = os.path.join(GAME, "BepInEx", "Translation", "en", "Text", "_AutoGeneratedTranslations.txt")
BASE_RESIZE_DIR = os.path.join(GAME, "BepInEx", "Translation", "en", "Text")

# Source of the third-party notices shipped next to the plugin (copied by publish.py when it exists), and the plugin source
# publish.py reads the rule loader's field list from.
NOTICES_SRC = os.path.join(REAL_LOCALIZATION, "src", "LOM_UI_EN", "THIRD_PARTY_NOTICES.txt")
PLUGIN_SRC = os.path.join(REAL_LOCALIZATION, "src", "LOM_UI_EN", "LOM_UI_EN.cs")
PLUGIN_BUILD_DLL = os.path.join(REAL_LOCALIZATION, "src", "LOM_UI_EN", "bin", "LOM_UI_EN.dll")

DEFAULT_PLUGIN = os.path.join(GAME, "BepInEx", "plugins", "LOM_UI_EN")
DEFAULT_WORKSPACE = os.path.join(REAL_LOCALIZATION, "workspace")
DEFAULT_BASE_REF = os.path.join(REAL_LOCALIZATION, "base_ref")
DEFAULT_BACKUPS = os.path.join(REAL_LOCALIZATION, "backups")

STAGE = None          # the staging root when stage() is in effect


def real(p):
    """p made absolute with every alias resolved (os.path.realpath: 8.3 short names such as C:\\PROGRA~2, junctions, symbolic
    links; a path that does not exist yet is resolved as far as it exists)."""
    a = os.path.abspath(p)
    try:
        return os.path.realpath(a)
    except (OSError, ValueError):
        return a


def _canon(p):
    return os.path.normcase(real(p))


def same_path(a, b):
    """a and b name the same file or folder (resolved, case-folded; os.path.samefile when both exist)."""
    if _canon(a) == _canon(b):
        return True
    try:
        return os.path.exists(a) and os.path.exists(b) and os.path.samefile(a, b)
    except OSError:
        return False


def inside(path, root):
    """path is root or lies under it. Both are resolved first (real()), so an 8.3 short name, a junction or a symbolic link
    cannot pass for another folder; where realpath leaves an alias (a share of a local folder), every existing ancestor of
    path is also compared with root by os.path.samefile."""
    a, b = _canon(path), _canon(root)
    if a == b or a.startswith(b.rstrip(os.sep) + os.sep):
        return True
    if not os.path.exists(root):
        return False
    p = real(path)
    while True:
        try:
            if os.path.exists(p) and os.path.samefile(p, root):
                return True
        except OSError:
            pass
        q = os.path.dirname(p)
        if q == p:
            return False
        p = q


def is_link(path):
    """path is a symbolic link or a junction (a mount point)."""
    try:
        return os.path.islink(path) or (hasattr(os.path, "isjunction") and os.path.isjunction(path))
    except OSError:
        return False


def long_path(p):
    """p made absolute as a Win32 long path (the \\\\?\\ prefix): no 260-character limit, and a name ending in a dot or a
    space is opened as it is instead of being trimmed to another name."""
    bs = chr(92)
    lp = bs + bs + "?" + bs
    a = os.path.abspath(p)
    if os.name != "nt" or a.startswith(lp):
        return a
    if a.startswith(bs + bs):
        return lp + "UNC" + bs + a[2:]
    return lp + a


def links_under(root, limit=20):
    """The symbolic links and junctions below root (not followed; root itself is not counted), at most limit of them, walked
    by long paths; a folder that cannot be opened is listed too (marked so). A folder publish.py writes into must hold none:
    a link inside it would carry a write (or a removal) somewhere else."""
    lroot = long_path(root).rstrip(chr(92))
    back = lambda p: os.path.join(root, p[len(lroot):].lstrip(chr(92)))     # the path again in root's own spelling
    out, stack = [], [lroot]
    while stack and len(out) < limit:
        d = stack.pop()
        try:
            it = os.scandir(d)
        except OSError as e:
            if os.path.lexists(d):
                out.append("%s (a folder that cannot be opened: %s)" % (back(d), e.strerror or e))
            continue
        with it:
            for e in it:
                try:
                    if e.is_symlink() or (hasattr(e, "is_junction") and e.is_junction()):
                        out.append(back(e.path))
                    elif e.is_dir(follow_symlinks=False):
                        stack.append(e.path)
                except OSError:
                    continue
    return out


def _protected():
    """Folders no maintainer tool may write into except through publish.py's own guarded writer (the plugin folder)."""
    return (os.path.join(GAME, "Mods"), os.path.join(GAME, "BepInEx", "Translation"), DEFAULT_PLUGIN, TOOLS,
            os.path.join(REAL_LOCALIZATION, "src"))


def guard_write(path):
    """Refuse a write of the maintainer data (workspace, base_ref, backups, logs) that would land inside the OverLlm patch's
    folders, the plugin folder, the tools or the plugin source, or, in stage mode, outside the stage (paths resolved first).
    Returns path."""
    for q in _protected():
        if inside(path, q):
            raise PermissionError("lom_paths: refusing to write %s: it is or lies inside %s" % (path, q))
    if STAGE is not None and not inside(path, STAGE):
        raise PermissionError("lom_paths: refusing to write %s: in stage mode (%s) every write stays inside the stage" % (path, STAGE))
    return path


def _home():
    """The folder all maintainer output belongs under: the stage in stage mode, LOM_Localization otherwise."""
    return STAGE if STAGE is not None else REAL_LOCALIZATION


def guard_under(path, root):
    """guard_write, and path must really lie inside root (both resolved: a junction, a link or an 8.3 name inside root cannot
    carry the write elsewhere, and '..' in a name cannot leave it), and root itself inside the stage (stage mode) or
    LOM_Localization. For the tools' change-log, backup and staged output folders and the files in them. Returns path."""
    if not inside(root, _home()):
        raise PermissionError("lom_paths: refusing to write %s: %s resolves to %s, outside %s (a junction or link?)" % (
            path, root, real(root), _home()))
    if not inside(path, root):
        raise PermissionError("lom_paths: refusing to write %s: it resolves to %s, outside %s (a junction or link, or a name "
                              "with '..'?)" % (path, real(path), root))
    return guard_write(path)


def _out_dir(d, root):
    guard_under(d, root)
    os.makedirs(d, exist_ok=True)
    return guard_under(d, root)         # again once it exists: what it resolves to now is what the files land in


def log_dir(name):
    """LOCALIZATION/<name>, created: where a tool's --live change log goes (guard_under LOCALIZATION: a name with '..' or a
    folder that is a junction or link to somewhere else is refused)."""
    if not name or os.path.isabs(name) or os.path.splitdrive(name)[0]:
        raise PermissionError("lom_paths: %r is not a folder name under %s" % (name, LOCALIZATION))
    return _out_dir(os.path.join(LOCALIZATION, name), LOCALIZATION)


def _hardlinked(p):
    try:
        return os.path.isfile(p) and os.stat(p).st_nlink > 1
    except OSError:
        return False


def out_path(folder, name):
    """A file to write in a guarded output folder (log_dir, staged_dir, new_backup_dir): not a link, junction or hard link
    (a write would land in the other name's file too), resolved inside it."""
    p = os.path.join(folder, name)
    if is_link(p) or _hardlinked(p):
        raise PermissionError("lom_paths: refusing to write %s: it is a link, junction or hard link" % p)
    return guard_under(p, folder)


def new_backup_dir(prefix, stamp):
    """A new, empty BACKUPS/<prefix>-<stamp>[-n] folder, created (guard_under BACKUPS)."""
    d, n = os.path.join(BACKUPS, "%s-%s" % (prefix, stamp)), 2
    while os.path.lexists(d):
        d, n = os.path.join(BACKUPS, "%s-%s-%d" % (prefix, stamp, n)), n + 1
    guard_under(d, BACKUPS)
    os.makedirs(d)
    return guard_under(d, BACKUPS)


def configure(plugin=None, workspace=None, base_ref=None, backups=None, localization=None):
    """Point the layout at the given folders (defaults: the real ones) and recompute every derived path. LOCALIZATION is
    where the apply tools put their change logs (LOM_Localization/<pass>/...) and their non-live output (staged/<tool>)."""
    g = globals()
    g["LOCALIZATION"] = localization or REAL_LOCALIZATION
    g["PLUGIN"] = plugin or DEFAULT_PLUGIN
    g["WORKSPACE"] = workspace or DEFAULT_WORKSPACE
    g["BASE_REF"] = base_ref or DEFAULT_BASE_REF
    g["BACKUPS"] = backups or DEFAULT_BACKUPS

    # ---- WORKSPACE: the full working data; the only translation files the editing tools may write.
    g["WS_TRANSLATION"] = os.path.join(WORKSPACE, "translation")
    g["TABLE"] = os.path.join(WS_TRANSLATION, "StringTable.csv")                 # key,"text" rows; the game-data string table
    g["SCENE_DIR"] = os.path.join(WS_TRANSLATION, "scene")
    g["SCENE"] = os.path.join(SCENE_DIR, "scene_text.txt")                       # XUnity-format zh=en lines for scene text
    g["WS_RESIZE_DIR"] = os.path.join(SCENE_DIR, "resize")                       # this mod's own *.resizer.txt (optional)
    g["STRINGS_DIR"] = os.path.join(WORKSPACE, "strings")                        # LOM_Strings_EN wording fixes (*.csv), full notes
    g["WS_RULES_DIR"] = os.path.join(WORKSPACE, "rules")                         # layout rules (*.json) with their comments
    g["WS_SENTINELS"] = os.path.join(WORKSPACE, "sentinels.json")                # data-check sentinel keys + hashes (no text)
    g["WS_LOCK"] = os.path.join(WORKSPACE, "base_ref.lock")                      # the BASE_REF md5s this workspace is aligned with
    g["WS_NAMETIPS"] = os.path.join(WORKSPACE, "nametips.tsv")                   # dialog name tips (ids, name forms, crops; no text)
    g["WS_FACTIONTIPS"] = os.path.join(WORKSPACE, "factiontips.tsv")             # faction tips (forms + this mod's descriptions)
    g["WS_RECORD"] = os.path.join(WS_TRANSLATION, "revision_record.tsv")         # per revised row: the hashes it was revised against
    g["WS_LEDGER"] = os.path.join(WS_TRANSLATION, "reviewed.tsv")                # review ledger: reviewed table keys (ledger.py)
    g["WS_SCENE_LEDGER"] = os.path.join(SCENE_DIR, "reviewed_scene.tsv")         # review ledger: reviewed scene lines (raw keys)

    # ---- BASE_REF: the OverLlm release the workspace diverged from (never shipped; replaced by publish.py rebase).
    g["BASE_REF_TABLE"] = os.path.join(BASE_REF, "StringTable.csv")
    g["BASE_REF_SCENE"] = os.path.join(BASE_REF, "_AutoGeneratedTranslations.txt")
    g["BASE_REF_RESIZE_DIR"] = os.path.join(BASE_REF, "resize")
    g["BASE_REF_SOURCE"] = os.path.join(BASE_REF, "game_source.tsv")           # the game's Chinese per key (srcdump), optional
    g["BASE_REF_INFO"] = os.path.join(BASE_REF, "base_ref.json")
    g["BASE_REF_HISTORY"] = os.path.join(BASE_REF, "history")                   # earlier releases the workspace was aligned with
    # 0.4 names: the "built-in original" (plugins/LOM_UI_EN/profiles/original) is gone since 0.5; the same text is BASE_REF.
    g["ORIG_DIR"] = BASE_REF
    g["ORIG_TABLE"] = BASE_REF_TABLE
    g["ORIG_SCENE"] = BASE_REF_SCENE

    # ---- PLUGIN: the shipped files, written only by publish.py's own guarded writer.
    g["TRANSLATION"] = os.path.join(PLUGIN, "translation")
    g["SHIP_TABLE"] = os.path.join(TRANSLATION, "StringTable.csv")
    g["SHIP_META"] = os.path.join(TRANSLATION, "StringTable.meta.tsv")
    g["SHIP_SCENE_DIR"] = os.path.join(TRANSLATION, "scene")
    g["SHIP_SCENE"] = os.path.join(SHIP_SCENE_DIR, "scene_text.txt")
    g["SHIP_MANIFEST"] = os.path.join(TRANSLATION, "MANIFEST.json")
    g["SHIP_STATE"] = os.path.join(TRANSLATION, ".publish_state.json")          # hashes of what the last publish wrote
    g["SHIP_STRINGS_DIR"] = os.path.join(PLUGIN, "strings")
    g["SHIP_RULES_DIR"] = os.path.join(PLUGIN, "rules")
    g["SHIP_RESIZE_DIR"] = os.path.join(SHIP_SCENE_DIR, "resize")                # this mod's own resizers only (0.4 copies removed)
    g["SHIP_PROFILES_DIR"] = os.path.join(PLUGIN, "profiles")                    # not shipped since 0.5 (removed by publish)
    g["SHIP_NOTICES"] = os.path.join(PLUGIN, "THIRD_PARTY_NOTICES.txt")
    g["MANIFEST"] = SHIP_MANIFEST                                                # 0.4 name
    g["RESIZE_DIR"] = SHIP_RESIZE_DIR                                            # 0.4 name
    g["UNTRANSLATED"] = os.path.join(TRANSLATION, "untranslated.txt")           # written by the game: scene<TAB>path<TAB>escaped zh
    g["RULES_DIR"] = WS_RULES_DIR                                                # rules are edited in the workspace since 0.5


def stage(root):
    """Move PLUGIN, WORKSPACE, BASE_REF, BACKUPS and LOCALIZATION under a staging root (root/plugin, root/workspace, ...).
    Refuses a root that is, holds or lies inside the game folder or LOM_Localization (it would alias the real folders), and
    a stage whose plugin, workspace, base_ref, backups or localization folder resolves outside the stage (a junction or link
    to a real folder). Every path is resolved first (8.3 short names, junctions, links)."""
    global STAGE
    root = real(root)
    for r in (GAME, REAL_LOCALIZATION, DEFAULT_PLUGIN, os.path.join(GAME, "Mods"), os.path.join(GAME, "BepInEx")):
        if inside(root, r) or inside(r, root):
            raise ValueError("lom_paths.stage: refusing staging root %s: it is, holds or lies inside %s (a stage must be a "
                             "separate folder, e.g. in the session scratchpad)" % (root, r))
    parts = {n: os.path.join(root, n) for n in ("plugin", "workspace", "base_ref", "backups", "localization")}
    for n, p in parts.items():
        if not inside(p, root):
            raise ValueError("lom_paths.stage: refusing staging root %s: its %s folder resolves to %s, outside the stage (a "
                             "junction or link?)" % (root, n, real(p)))
    configure(plugin=parts["plugin"], workspace=parts["workspace"], base_ref=parts["base_ref"], backups=parts["backups"],
              localization=parts["localization"])
    STAGE = root
    return root


configure()
if os.environ.get("LOM_STAGE"):
    try:
        stage(os.environ["LOM_STAGE"])
    except ValueError as _e:
        sys.exit(str(_e))


def assert_writable(path):
    """Refuse to write anything but the workspace table and scene file (the shipped files are written by publish.py only,
    and the base patch's files are not ours to edit). Paths are resolved first, so an alias of another file (an 8.3 short
    name, a junction, a link) is judged by what it really names; the workspace itself must not resolve into a protected
    folder, nor outside the stage in stage mode."""
    p = _canon(path)
    if p not in {_canon(TABLE), _canon(SCENE)} and not any(same_path(path, q) for q in (TABLE, SCENE)):
        raise PermissionError("lom_paths: refusing to write %s; tools may only write %s or %s (the plugin folder is written by "
                              "publish.py)" % (path, TABLE, SCENE))
    return _assert_ws_file(path)


def assert_ledger_writable(path):
    """assert_writable for the two review ledger files (WS_LEDGER, WS_SCENE_LEDGER), which ledger.py writes: nothing else,
    resolved inside the workspace (and the stage), not a hard link, in a folder that exists."""
    p = _canon(path)
    if p not in {_canon(WS_LEDGER), _canon(WS_SCENE_LEDGER)} and not any(same_path(path, q) for q in (WS_LEDGER, WS_SCENE_LEDGER)):
        raise PermissionError("lom_paths: refusing to write %s; the ledger writer may only write %s or %s" % (
            path, WS_LEDGER, WS_SCENE_LEDGER))
    return _assert_ws_file(path)


def assert_nametips_writable(path):
    """assert_writable for workspace/nametips.tsv and factiontips.tsv (WS_NAMETIPS, WS_FACTIONTIPS), which
    tools/nametips/nametips.py writes: nothing else, resolved inside the workspace (and the stage), not a hard link."""
    if not any(_canon(path) == _canon(q) or same_path(path, q) for q in (WS_NAMETIPS, WS_FACTIONTIPS)):
        raise PermissionError("lom_paths: refusing to write %s; the name tips tool may only write %s or %s" % (
            path, WS_NAMETIPS, WS_FACTIONTIPS))
    return _assert_ws_file(path)


def _assert_ws_file(path):
    if not inside(path, WORKSPACE):
        raise PermissionError("lom_paths: refusing to write %s: it resolves to %s, outside the workspace %s (a junction or "
                              "link?)" % (path, real(path), WORKSPACE))
    if _hardlinked(path):
        raise PermissionError("lom_paths: refusing to write %s: it is a hard link (a write would change the other name's file "
                              "too)" % path)
    guard_write(path)
    if not os.path.exists(os.path.dirname(path)):
        raise FileNotFoundError("lom_paths: %s does not exist; the workspace is created by cutover_0_5.py" % os.path.dirname(path))
    return path


def backup_path(path, stamp):
    """LOM_Localization/backups/<file name>.<stamp>.bak, as the older tools named their backups; a free name (…-2, -3) when
    that one is taken, so two runs in the same second each keep their own backup."""
    base = os.path.join(BACKUPS, os.path.basename(path) + "." + stamp)
    p, n = base + ".bak", 2
    while os.path.lexists(p):
        p = "%s-%d.bak" % (base, n)
        n += 1
    return guard_under(p, BACKUPS)


def staged_dir(name):
    """Where a tool's non-live run puts its output (full tables included): LOCALIZATION/staged/<name>, so under LOM_STAGE it
    lands in the stage, and never in the tools folder (guard_under LOCALIZATION: a junction there is refused)."""
    return _out_dir(os.path.join(LOCALIZATION, "staged", name), LOCALIZATION)


def take_keep_record(argv=None):
    """For the apply tools: take '--keep-record KEYS|@FILE|all' (or '--keep-record=...') out of argv (default sys.argv) and
    return its value (None when absent), for publish(keep_record=...). Exits with a message when the value is missing or
    names a file that does not exist, before the tool writes anything."""
    argv = sys.argv if argv is None else argv
    val = None
    i = 1
    while i < len(argv):
        a = argv[i]
        if a == "--keep-record":
            if i + 1 >= len(argv) or argv[i + 1].startswith("--"):
                sys.exit("--keep-record needs a value: KEYS (comma-separated), @FILE or all")
            val = argv[i + 1]
            del argv[i:i + 2]
            continue
        if a.startswith("--keep-record="):
            val = a.split("=", 1)[1]
            del argv[i]
            continue
        i += 1
    if val is not None and (not val or (val.startswith("@") and not os.path.isfile(val[1:]))):
        sys.exit("--keep-record %s: %s" % (val, "no such file" if val else "empty value"))
    return val


def publish(target=None, force=False, exit_on_failure=True, keep_record=None):
    """Rebuild the shipped files from the workspace (publish.py build, in process) and print a one-line summary.

    Called by every tool after a live write to TABLE or SCENE. The workspace write already happened, so a failure only
    concerns the plugin folder: it prints why and exits with code 3 (not published: a shipped file edited by hand, a check
    failure before writing, an interrupted write) or 4 (written, but the check of the written files fails), or returns None
    when exit_on_failure is False. Returns the build result on success. keep_record: publish.py build --keep-record
    (the tool's own --keep-record, take_keep_record)."""
    import importlib.util
    spec = importlib.util.spec_from_file_location("lom_publish", os.path.join(os.path.dirname(os.path.abspath(__file__)), "publish.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    cmd = "python %s build" % os.path.join(TOOLS, "publish.py")
    if keep_record:
        cmd += ' --keep-record "%s"' % keep_record
    code = 0
    try:
        res = mod.build(target or PLUGIN, force=force, verbose=False, keep_record=keep_record)
    except mod.WrittenCheckFailed as e:
        print("publish: WRITTEN, but the check of the written files fails (%s); the workspace is saved and the plugin folder "
              "holds the new files: fix the workspace and run: %s" % (e, cmd))
        code = 4
    except mod.PublishError as e:
        print("publish: NOT published (%s); the workspace is saved, fix that and run: %s" % (e, cmd))
        code = 3
    except OSError as e:
        print("publish: NOT published (interrupted: %s); the workspace is saved; run: %s" % (e, cmd))
        code = 3
    if code:
        if exit_on_failure:
            sys.exit(code)
        return None
    print("publish: " + res["summary"])
    return res
